### PR TITLE
MRG: Add __file__

### PR DESCRIPTION
**Pull request by Eric89GXL**
In one of my scripts I want to use `__name__` but in `master` it is not available.

### CODE REVIEW

**Comment by Eric89GXL** [comment]
... and by `__name__` I mean `__file__`

**Comment by Eric89GXL** [comment]
Travis is happy, ready for review/merge from my end

**Comment by lesteve** [comment]
LGTM, merging thanks!

**Comment by lesteve** [comment]
@Eric89GXL actually thinking about it more, `example_file` is something like `auto_examples/plot_seaborn.py`, is that what you expected? I would have thought that it should point to the example i.e. either `examples/plot_seaborn.py` or maybe even better its absolute path.

**Comment by Eric89GXL** [comment]
Yeah pointing to the actual original python file would be best

**Comment by lesteve** [comment]
> Yeah pointing to the actual original python file would be best

PR welcome ;-) !

**Comment by GaelVaroquaux** [comment]
I just thought about something: it seems that __name__ is defined in an IPython notebook, but not __file__.

I would hence be in favor of not supporting __file__. It's going to confuse users that run things in IPython notebooks.

**Comment by Eric89GXL** [comment]
That's true. However, any example that a given project has that uses `__file__` already has this problem, and thus we aren't making anything worse by supporting it, except maybe because of the IPython-notebook download button. Maybe we should disable that for any example file that uses `__file__`?

**Comment by GaelVaroquaux** [comment]
> That's true. However, any example that a given project has that uses __file__
> already has this problem, and thus we aren't making anything worse by
> supporting it, except maybe because of the IPython-notebook download button.

The problem is that users are strongly demanding the IPython notebook
feature. These users expect examples to work in IPython notebooks.

> Maybe we should disable that for any example file that uses __file__?

Why do examples need the file? IMHO they should be rewritten. People will
copy-paste them in IPython notebooks and run into problems.

By supporting __file__ in sphinx-gallery you are just hidding this
problem.

The core problem is that Python now has several execution models and that
they are not compatible. It's a problem created by notebook, and not by
sphinx-gallery.

**Comment by Eric89GXL** [comment]
Fair enough. Feel free to roll back the commit in `master`

**Comment by GaelVaroquaux** [comment]
> Fair enough. Feel free to roll back the commit in master

Will you be able to adapt your example?

**Comment by Eric89GXL** [comment]
Yeah, after some tweaking I got it working using a different tactic than `__file__`. I don't know if it will work in all cases, but at least it did here.

**Comment by GaelVaroquaux** [comment]
I reverted, but stopped short of documenting this behavior, because if
it's a major blocker for many people we will support __file__.

**Comment by lesteve** [comment]
Good catch @GaelVaroquaux !

**Pull request merged**
