### PR TITLE
[WIP] Bugfix missing parent div for mini gallery

### LINKED ISSUE #911: mini-gallery not shown in grid
Hello and thank you very much for this awesome code!

I noticed in the last compilation of the (dev) doc of POT : 
https://pythonot.github.io/master/quickstart.html#examples-of-use-for-ot-emd

that the mini-galleries do not show proper grids see screenshot below:
image
which takes tons of space.

Here is the code in the rst file for the gallery above:
```
.. minigallery:: ot.emd2
    :add-heading: Examples of use for :any:`ot.emd2`
    :heading-level: "
```

This is a bit sad because I really like the new css grids that can handle long titles with no problems ;).

I'm pinging @alexisthual who probably knows what to do about this.

### PR DESCRIPTION
**Pull request by alexisthual**
Closes #911.

### CODE REVIEW

**Comment by alexisthual** [comment]
Also, it is not clear to me why [one test fails](https://dev.azure.com/sphinx-gallery/sphinx-gallery/_build/results?buildId=565&view=logs&j=0b648da4-fe3e-53a0-45c5-9a162ff06918&t=684eab53-20d4-5801-24d9-b15ea59a3d0b&l=219)

The stacktrace is the following:
```
=================================== FAILURES ===================================
___________________________ test_save_mayavi_figures ___________________________
sphinx_gallery/tests/test_scrapers.py:117: in test_save_mayavi_figures
    from mayavi import mlab
/usr/share/miniconda/lib/python3.7/site-packages/mayavi/mlab.py:16: in <module>
    from mayavi.tools.camera import view, roll, yaw, pitch, move
/usr/share/miniconda/lib/python3.7/site-packages/mayavi/tools/camera.py:24: in <module>
    from .engine_manager import get_engine
/usr/share/miniconda/lib/python3.7/site-packages/mayavi/tools/engine_manager.py:14: in <module>
    from mayavi.core.engine import Engine
/usr/share/miniconda/lib/python3.7/site-packages/mayavi/core/engine.py:28: in <module>
    from mayavi.core.scene import Scene
/usr/share/miniconda/lib/python3.7/site-packages/mayavi/core/scene.py:15: in <module>
    from mayavi.core.source import Source
/usr/share/miniconda/lib/python3.7/site-packages/mayavi/core/source.py:23: in <module>
    from mayavi.core.adder_node import ModuleFilterAdderNode
/usr/share/miniconda/lib/python3.7/site-packages/mayavi/core/adder_node.py:16: in <module>
    from pyface.api import ImageResource
/usr/share/miniconda/lib/python3.7/site-packages/pyface/api.py:105: in <module>
    from .about_dialog import AboutDialog
/usr/share/miniconda/lib/python3.7/site-packages/pyface/about_dialog.py:17: in <module>
    AboutDialog = toolkit_object("about_dialog:AboutDialog")
/usr/share/miniconda/lib/python3.7/site-packages/pyface/base_toolkit.py:127: in __call__
    module = import_module(mname, package)
/usr/share/miniconda/lib/python3.7/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
/usr/share/miniconda/lib/python3.7/site-packages/pyface/ui/qt4/about_dialog.py:20: in <module>
    from .dialog import Dialog
/usr/share/miniconda/lib/python3.7/site-packages/pyface/ui/qt4/dialog.py:29: in <module>
    int(QtGui.QDialog.DialogCode.Accepted): OK,
E   AttributeError: type object 'DialogCode' has no attribute 'Accepted'
---------------------------- Captured stderr setup -----------------------------
Maybe try:

    sudo apt-get install pandoc
See http://johnmacfarlane.net/pandoc/installing.html
for installation options
---------------------------------------------------------------
```

Any idea how this could come from?

**Comment by larsoner** [comment]
> Any idea where this could come from?

Looks totally unrelated, so I restarted the CIs. I think it's safe to ignore for now even if it comes back red (i.e., not your problem!)

> It's weird, can you please try again?

Looks fine now -- maybe I didn't clean my Sphinx env properly or something last time!

Ready for merge from your end @alexisthual ?

**Comment by alexisthual** [comment]
Alright, tests seem to pass now (I didn't change anything).
I think it's safe to merge :slightly_smiling_face:

**Comment by lucyleeow** [comment]
Thanks @alexisthual !

**Pull request merged**
