### PR TITLE
ENH: Use Sphinx errors

### LINKED ISSUE #600: MAINT: Better error messages
As [pointed out](https://github.com/sphinx-gallery/sphinx-gallery/pull/599/files#r369287580) by @mgeier, raising plain Python errors is not as nice as raising Sphinx-specific variants. We should update our internal exceptions.

### PR DESCRIPTION
**Pull request by larsoner**
Use Sphinx errors rather than built-in ones when something goes wrong. This coupled with https://github.com/sphinx-doc/sphinx/pull/7699 should make sphinx dev work again. Should probably wait for that one to be merged before merging this one, hence the WIP label.

Closes #600

### CODE REVIEW

**Comment by larsoner** [comment]
@lucyleeow this one should be ready now

**Comment by choldgraf** [comment]
I had no idea that these error classes existed lol. Where did you find them in the sphinx docs?

I'm curious how this changes the behavior of `SG`...does it make the error messages more helpful or something? (+1 on the PR though)

**Comment by larsoner** [comment]
> I had no idea that these error classes existed lol. Where did you find them in the sphinx docs?

I really looked here:

https://www.sphinx-doc.org/en/master/_modules/sphinx/errors.html

But I guess the official docs are here:

https://www.sphinx-doc.org/en/master/extdev/appapi.html#exceptions

> I'm curious how this changes the behavior of SG...does it make the error messages more helpful or something?

The output is a bit cleaner. This is what a `ValueError` looks like:
```
Exception occurred:
  File "/home/larsoner/python/sphinx-gallery/sphinx_gallery/gen_rst.py", line 323, in _get_readme
    raise ValueError(
ValueError: Example directory /home/larsoner/python/sphinx-gallery/sphinx_gallery/tests/tinybuild/examplesy/ does not have a README file with one of the expected file extensions ['.txt', '.rst']. Please write one to introduce your gallery.
The full traceback has been saved in /tmp/sphinx-err-bvw0jkjo.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```
And this is the new one:
```
Extension error:
Example directory /home/larsoner/python/sphinx-gallery/sphinx_gallery/tests/tinybuild/examplesy/ does not have a README file with one of the expected file extensions ['.txt', '.rst']. Please write one to introduce your gallery.
```

**Comment by choldgraf** [comment]
ooh I love it, I should re-use those

**Comment by larsoner** [comment]
@lucyleeow you up for cutting a 0.7.0 release now?

**Comment by lucyleeow** [comment]
Sure will do it now.

**Pull request merged**
