### PR TITLE
Multiple Language Support

### PR DESCRIPTION
**Pull request by chsasank**
A follow up to #196. I've had to cherry pick my commits to fix the commit history of my branch.
I'm copying text from #196 and closing it.

Following discussion #194, I've made a working version with support for multiple languages. In the process, I've done quite a bit of refactoring.

I also 
- made some functions 'private' with prepending `_` to function names. 
- made some code pep8 complaint
- Added comments here and there

Please have a look at the implementation and give me your feedback.

Right now, I've written only lua parser, adding other languages shouldn't be hard at this point.

TODO:
- [x] Merge changes from Titan-C/sphinx-gallery:func_rst carefully.
- [ ] Add other language support
- [x] Fix Downloads bug (absolute path is being used to save zip) 
- [ ] Write Tests

### CODE REVIEW

**Comment by lesteve** [comment]
Is it already working for SimpleITK doc? I would be interested to look at the output.

**Comment by chsasank** [comment]
I have put it up here: https://chsasank.github.io/sitk-docs/auto_examples/index.html

**Comment by lesteve** [comment]
> I have put it up here: https://chsasank.github.io/sitk-docs/auto_examples/index.html

Thanks!

**Comment by larsoner** [comment]
@chsasank this PR has a pretty challenging rebase problem now. I'll close this PR but feel free to open a new one if you can get to it. Hopefully it's easier in the context of our recent refactoring!

**Pull request closed without merging**
