### PR TITLE
ENH: Add dev/stable distinction

### LINKED ISSUE #559: Documentation is ahead of current release
Currently documentation is built from master, meaning that the documentation is updated for new features not available in the current release. This can cause confusion ([esp for big changes](https://github.com/sphinx-gallery/sphinx-gallery/pull/541#issuecomment-552217045)).

Maybe we can update documentation with releases (like some other projects)?

### PR DESCRIPTION
**Pull request by larsoner**
Closes #559.

[EDIT: I manually created] ~~Created~~:

https://sphinx-gallery.github.io/dev/
https://sphinx-gallery.github.io/stable/

Currently just copies of https://sphinx-gallery.github.io/. Steps:

1. Make sure people are happy with how CircleCI renders the version drop-down, then merge this PR
2. Make sure that CircleCI deploys to https://sphinx-gallery.github.io/dev/
3. Release a new version
4. Make sure that CircleCI deploys to https://sphinx-gallery.github.io/stable/ based on the tag
5. Overwrite `https://sphinx-gallery.github.io/index.html` with a URL redirect and remove all other files other than `dev`/`stable` dirs, `index.html`, and `.nojekyll`.

### CODE REVIEW

**Comment by larsoner** [comment]
https://1108-25860190-gh.circle-artifacts.com/0/rtd_html/index.html

@choldgraf @lucyleeow let me know if this is a good enough start. If so we should merge so that I can work on step (2)

**Comment by choldgraf** [comment]
IMO this is good enough for me, I'll give it a merge so we can build in the rest of the process. We might want some CSS tweaks etc, but I think that we could improve this iteratively anyway :-)

**Comment by lucyleeow** [comment]
That looks good but I have a question - what is the purpose of the version drop down? Is it intended for people to be directed here so they can choose the dev/stable docs?

And where would you be redirecting to?
>     5\. Overwrite `https://sphinx-gallery.github.io/index.html` with a URL redirect and remove all other files other than `dev`/`stable` dirs, `index.html`, and `.nojekyll`.

**Comment by larsoner** [comment]
> what is the purpose of the version drop down? Is it intended for people to be directed here so they can choose the dev/stable docs?

Eventually the only docs that exist will be under the `/dev` and `/stable` directories. Then people can choose whether they want the stable docs corresponding to our latest `pip` release, or the dev docs in case they are using `master`.

`/index.html` will point to `/stable` since I assume most people work off of the stable `pip` version.

**Comment by lucyleeow** [comment]
FYI google results directing to any SG page that is not the home page (`index.html`) does not re-direct and you get 404 error. e.g.: the links to Configuration etc do not work. 

Not sure if it is easy to re-direct all pages?

image

**Comment by GaelVaroquaux** [comment]
You should investigate what's known as the Google search console, URL inspection, and how to define sitemaps to Google. 

⁣Sent from my phone. Please forgive typos and briefness.​

**Comment by larsoner** [comment]
I got ownership and sitemap access. However, it looks like wildcards are not supported for sitemaps. So it might be easier to make `N_old` `html` files that redirect properly, rather than `N_old + N_new_dev + N_new_stable` in a sitemap (and maintain it!), unless I'm missing something about the site map.

Eventually it seems like google would catch on that those old pages don't exist, so even making redirects for the main pages might be a good enough start.

**Comment by larsoner** [comment]
I used this to generate redirects, run in the `sphinx-gallery.github.io` directory:
```
import os
import glob

template = """
<!DOCTYPE HTML>
<html lang="en-US">
    <head>
        <link rel="canonical" href="https://sphinx-gallery.github.io/stable/{0}">
        <meta charset="UTF-8">
        <meta http-equiv="refresh" content="1; url=https://sphinx-gallery.github.io/stable/{0}">
        <script type="text/javascript">
            window.location.href = "https://sphinx-gallery.github.io/stable/{0}"
        </script>
        <title>Page Redirection</title>
    </head>
    <body>
        If you are not redirected automatically, follow this <a href='https://sphinx-gallery.github.io/stable/{0}'>link</a>.
    </body>
</html>
"""

for name in sorted(glob.glob(os.path.join('stable', '*.html'))):
    name = os.path.basename(name)
    with open(name, 'w') as fid:
        fid.write(template.format(name))
```
Made 15 HTML files like:

https://github.com/sphinx-gallery/sphinx-gallery.github.io/blob/master/index.html

The `<link rel="canonical"` should hopefully be enough for Google to update itself.

This didn't redirect the `auto_examples`, `auto_mayavi_examples`, or `generated` pages but I think it should be good enough.

**Pull request merged**
