### PR TITLE
Activating travis on pre-release of python

### PR DESCRIPTION
**Pull request by NelleV**
Activating travis on 3.7 and nightly build of latest dev (with allowed failure, currently python 3.8 which is in pre-release, and apparently breaks sphinx-gallery (unchecked)).

### CODE REVIEW

**Comment by NelleV** [comment]
It fails, but not for the right reasons. I'll try to fix this later.

**Comment by NelleV** [comment]
The remaining errors on the sphinx-gallery are real.

**Comment by NelleV** [comment]
I'm not sure why the coverage went down: I've added matrix entries, and haven't removed any.

**Comment by larsoner** [comment]
> I'm not sure why the coverage went down: I've added matrix entries, and haven't removed any.

Agreed. Codecov has some questionable statistics, I think we can safely ignore it here.

If you're done, +1 for merge from me, and we can fix the nightly errors in a subsequent PR. I can try to look in the coming days if it would help.

**Comment by larsoner** [comment]
Okay in it goes, let's fix the issues in another PR

**Comment by larsoner** [comment]
Thanks @NelleV

**Comment by choldgraf** [comment]
wooo, thanks @NelleV !

(on a side-note, I accidentally started with `:` when I was looking for nelle's username above, and I discovered that apparently there is now a "neckboard" emoji: :neckbeard: )

**Pull request merged**
