### PR TITLE
ENH: Remove some Sphinx markup from text

### LINKED ISSUE #497: ENH: remove API crossrefs from hover text
Currently if the first sentence of an example/tutorial/whatever contains an API cross-ref, the hover text can end up looking like this:

Screenshot_2019-05-28_11-33-48

Enhancement would be to add a regex to the hover text generator that would strip out the cross-reference-generating text and leave just the class/function/method/attribute name. Ideally would be smart enough to behave the same way the cross-refs do w/r/t the presence of the leading `~`.

### PR DESCRIPTION
**Pull request by larsoner**
Closes #497.

@drammock can you review and see if this fixes the problem for you? Locally for me it fixes the issue you posted about.

### CODE REVIEW

**Comment by drammock** [comment]
Thanks for doing this (I meant to do it myself, but hadn't gotten to it yet).

I didn't do a thorough test of all the possibilities, but it does work for all the current MNE-Python tutorials.  In MNE-Python examples there is one tooltip ("plot a cortical parcellation") that still renders as this:

```
In this example, we download the HCP-MMP1.0 parcellation [1]_ and show it on ``fsaverage``. We ...
```

and another one ("show noise levels from empty room data") that has a tooltip

```
This shows how to use :meth:`mne.io.Raw.plot_psd` to examine noise levels of systems. See [1]_ ...
```

Would be nice if it stripped links, backticks, and `:meth:` roles too (not sure how it handles `:attr:`, `:func:`, `:doc:`, or `:math:` roles, to name the ones we most often use), but if you don't feel like doing that now I'm fine to merge as-is and tackle that improvement myself in a separate PR.

**Comment by drammock** [comment]
actually I'm not sure stripping links is such a good idea. Just saw a tooltip that says:

```
This example runs the analysis described in [1]_. It illustrates how one can fit a linear class...
```

I'd say that's a poor job of writing the opening sentence, but stripping the `[1]_` will just make it worse.

**Comment by larsoner** [comment]
Okay the two cases for `plot_psd` and `fsaverage` should now be fixed, can you try again @drammock ?

**Comment by drammock** [comment]
@larsoner I confirm that this fixes those two cases.

**Comment by larsoner** [comment]
@choldgraf feel free to merge and I'll cut a release

**Comment by choldgraf** [comment]
🚢

**Pull request merged**
