### PR TITLE
Add note on Jupytext to bypass RTD for Binder integration

### PR DESCRIPTION
**Pull request by StanczakDominik**
Hey, I guess I'm really laser focused on this one aspect :D this is a follow up to #505. I came across this Jupytext solution to the problem I had before, and thought it would be nice to mention this here.

### CODE REVIEW

**Comment by choldgraf** [comment]
Hmmm - this seems a little bit hacky to me (particularly because we don't really link to a full set of instructions, just to jupytext itself). Could you write up a short little blog post (or a post in [the jupyter community forum](https://discourse.jupyter.org)) that we can link to from here?

**Comment by StanczakDominik** [comment]
Sure. Is it fine if I put it on https://stanczakdominik.github.io ?

**Comment by StanczakDominik** [comment]
And yes, it is awfully hacky. :sweat_smile:

**Comment by choldgraf** [comment]
it's fine w/ me - @larsoner what do you think?

**Comment by larsoner** [comment]
No string opinion, I defer to your judgment

**Comment by choldgraf** [comment]
@larsoner what about a `float` opinion? ;-)

**Comment by larsoner** [comment]
+0.5 :)

**Comment by choldgraf** [comment]
@StanczakDominik let us know when you've got a guide posted and a link to it in this PR!

**Comment by StanczakDominik** [comment]
Sure! I wanted to finish my implementation of this in PlasmaPy first, to be able to show a working example, and unrelated but blocking bugs just started flooding out of the woodwork everywhere like it's a cheap horror movie. I'll have it done in a couple of days.

**Comment by StanczakDominik** [comment]
Here it is:

https://stanczakdominik.github.io/posts/simple-binder-usage-with-sphinx-gallery-through-jupytext/

I guess I'll just stick it in the docs, then!

**Comment by StanczakDominik** [comment]
All right, with this posted, I would like to ask you if this kind of solution is something you'd be interested in supporting out of the box without monkey patching the gallery example URLs, or if this is too hacky - because I'll be the first to admit it is terribly hacky.

**Comment by larsoner** [comment]
I at least am open to new functionality that in general:

1. Does not break existing functionality, or change it (unless it can be considered bug fix or worth deprecating)
2. Will be widely used
3. Makes things easier for people to use SG
4. Has low maintenance burden (additional install dependencies for CIs, properly testable, etc.) or someone volunteering to maintain it for a while (timescale of years not months)

I haven't looked closely, but if you could give us a sense of the extent to which it meets or violates these criteria it would help. Maybe tell us what problem it solves, ballpark/order of magnitude how many lines you think it would take to support it properly, additional dependencies (and their stability)? I could look deeper and try to infer from the code myself if you're unsure.

**Comment by StanczakDominik** [comment]
Okay, I should definitely have been more clear there, my apologies.

What I'm proposing is optionally allowing `binder.gen_binder_url` to switch from returning, with `baseurl = "https://gke.mybinder.org/v2/gh/PlasmaPy/PlasmaPy/master"` for my use case:

    {baseurl}?filepath=plasmapy/examples/auto_examples/plot_physics.ipynb

to returning something like this:

    {baseurl}}?filepath=plasmapy/examples/plot_physics.py

In other words, `gallery_conf['gallery_dirs']` is not added to the path and the file extension is kept as `.py` rather than `.ipynb`.

A simple but hacky monkeypatching implementation via `gen_binder_rst` (it was simpler to modify, with less lines of code) is in the blog post above, near the end.

This allows the Binder link to point to an actual sphinx-gallery `.py` file in the existing repository. With added `binder/requirements.txt` and `jupyter/jupyter_notebook_config.py` files, this gives you sphinx-gallery to Binder support with no extra effort, with the standard ReadTheDocs et cetera doc building infrastructure.

To directly answer your (reasonable) conditions:

1. the sphinx-gallery part can be implemented via optional arguments, off by default. I'm not yet sure what the best way of achieving this is.
2. This basically lets everyone who's using sphinx-gallery with RTD have simple Binder support in three steps (two files and a change to `conf`.py`). Assuming everyone who's got examples would like them to be interactive, that's pretty much [everyone in "Who uses Sphinx-Gallery"](https://github.com/sphinx-gallery/sphinx-gallery#who-uses-sphinx-gallery) who doesn't self-host documentation.
3. As things are now, you need to monkeypatch `sphinx_gallery.binder` to do this cleanly. Implementing this would mean people still need to set those two files up, but at least it cuts the monkey patching.
4. A string comparison test for an optional argument is pretty simple to write. I'm not sure how one would test the full integration. I'm gonna be using this in PlasmaPy for a good while; I can volunteer for maintenance.

**Comment by larsoner** [comment]
This sounds reasonable to me. @choldgraf as the resident binder expert, okay with you? @jasmainak would this have helped with any of the problems we had with MNE?

**Comment by jasmainak** [comment]
yes perhaps, could this allow arbitrary file paths? For example, we wanted to have different links for [different versions of MNE](https://github.com/mne-tools/mne-tools.github.io).

**Comment by choldgraf** [comment]
Ah interesting. Im +1 in theory on this, though I'm a bit worried we'd confuse people if they get pointed to a py file that shows up as a notebook file. We should demo this to see what the UX feels like

One potential blocker here is adding a dependency to jupytext... If I recall, I suggested replacing our notebook generation code so that it used jupytext instead of our own scripts, but I got pushback from folks that didn't want to add the dependency...

**Comment by GaelVaroquaux** [comment]
Would the completion of https://github.com/sphinx-gallery/sphinx-gallery/issues/370 help to simplify the process here?

**Comment by StanczakDominik** [comment]
> Would the completion of #370 help to simplify the process here?

Sorry, isn't that a link mistake there?

**Comment by GaelVaroquaux** [comment]
> Sorry, isn't that a link mistake there?

Well, I was intending to point to this issue indeed.

I haven't looked at the process to integrate Jupytext and sphinx-gallery,
but the point being that if they shared the same separators, it might be
easier.

**Comment by StanczakDominik** [comment]
> Well, I was intending to point to this issue indeed. I haven't looked at the process to integrate Jupytext and sphinx-gallery, but the point being that if they shared the same separators, it might be easier.

Ah! Apologies, then, my mistake.

> One potential blocker here is adding a dependency to jupytext... If I recall, I suggested replacing our notebook generation code so that it used jupytext instead of our own scripts, but I got pushback from folks that didn't want to add the dependency...

Unless pushing ahead with replacing notebook generation code, I don't think a jupytext dependency is necessary here. The binder image needs to contain jupytext to render .py as `.ipynb`, but you can still use sphinx-gallery without it as usual - and simply use jupytext binder-side. If anything, it could go into extras as an optional dependency.

> Ah interesting. Im +1 in theory on this, though I'm a bit worried we'd confuse people if they get pointed to a py file that shows up as a notebook file. We should demo this to see what the UX feels like

Here's a sample (please ignore that the example is a WIP). I'm having trouble getting RTD to generate the links in other examples right now, but I think it's some caching issue.

http://docs.plasmapy.org/en/master/auto_examples/particle_stepper.html#sphx-glr-auto-examples-particle-stepper-py

**Comment by choldgraf** [comment]
I think we run the risk of confusing users if there are now 2 ways that notebooks get created from `.py` files (one in the sphinx gallery build process itself, and another via the documentation which suggests you can use jupytext to convert the `.py` files to notebooks on-the-fly in Binder).

@GaelVaroquaux I believe that @mwouts did add support for sphinx-gallery separators:

`%%` format: https://jupytext.readthedocs.io/en/latest/formats.html#the-percent-format
`SG default` format: https://jupytext.readthedocs.io/en/latest/formats.html#sphinx-gallery-scripts

**Comment by mwouts** [comment]
> I believe that @mwouts did add support for sphinx-gallery separators

Indeed - sphinx-gallery scripts are one of [the three formats](https://towardsdatascience.com/jupyter-notebooks-as-light-percent-or-sphinx-scripts-efca8bc3aa44) for notebooks as scripts supported by Jupytext. Use
```
jupytext --to py:sphinx notebook.ipynb
```
to convert a notebook to its sphinx-gallery representation.

Please note that installing Jupytext is enough to edit or render sphinx-gallery scripts as notebooks in Jupyter. The recommended configuration for Binder at https://jupytext.readthedocs.io/en/latest/formats.html#sphinx-gallery-scripts is a bit more verbose, to ensure
- that every python script is treated as a sphinx-gallery script (and not only those with two lines with twenty or more `#`...)
- and that the rST in the text cells is converted to markdown (this is done with `rst2md` from `sphinx_gallery.notebook`!)

**Pull request closed without merging**
