### PR TITLE
cached conda gives problems in new Circle CI Builds

### PR DESCRIPTION
**Pull request by Titan-C**
Shamelessly copy from MNE-python Circle CI script not to install conda again

### CODE REVIEW

**Comment by lesteve** [comment]
What problem does this solve?

**Comment by Titan-C** [comment]
> What problem does this solve?

Build on the same branch or PR start using the cache and then fail when conda tries to install. See

https://circleci.com/gh/Titan-C/sphinx-gallery/11

**Comment by lesteve** [comment]
I see, they are caching the miniconda install. Not sure I am a big fan of the idea, I'd rather remove ~/miniconda from the cache.

**Comment by Titan-C** [comment]
> I see, they are caching the miniconda install. Not sure I am a big fan of the idea, I'd rather remove ~/miniconda from the cache.

I see the cache is because one downloads a lot. Comparing timings for us downloading conda with mayavi and mkl + install takes a little more than a minute. For MNE-Python they need 3 min to recover their cache which includes more than the conda install. I'm fine with dropping the cache

**Comment by Titan-C** [comment]
It's a bit weird, but building without saving cache breaks the build because cache was already there. I'm rebuilding from CircleCi to clean everything

**Comment by lesteve** [comment]
Let's merge this one thanks!

**Pull request merged**
