### PR TITLE
MAINT: Fix for Sphinx 7.2

### LINKED ISSUE #1175: BUG Sphinx `docname` from source-read event is sometimes `None`
Doc build and several `test_full.py` tests on Windows CI workflow failing on recent PRs (e.g., #1173, #1172)

Windows `test_full.py` failures are all due to:
```
sphinx_gallery\gen_gallery.py:919: in write_api_entry_usage
    "sg_api_usage" not in docname
E   TypeError: argument of type 'NoneType' is not iterable
```
Similarly doc build error is:
```
An error happened in rendering the page advanced.
Reason: AttributeError("'TocTree' object has no attribute 'get_toctree_ancestors'")
```
AFAICT `docname` should: "Returns the docname of the document currently being parsed."
https://www.sphinx-doc.org/en/master/extdev/envapi.html#sphinx.environment.BuildEnvironment.docname

'source-read' event emits `env.docname` which  does not seem to have changed recently: https://github.com/sphinx-doc/sphinx/blob/da9f8a5c33ad5eeef05dd780f2988f3ff7351ef3/sphinx/environment/__init__.py#L545

Seems to be a Sphinx issue as there was a release some hours ago.

### PR DESCRIPTION
**Pull request by larsoner**
Closes #1175

### CODE REVIEW

**Comment by pllim** [comment]
Hi! Does this patch also fix this error I am seeing downstream with Sphinx 7.2.2 and sphinx-gallery 0.13.0 ?

```
Traceback (most recent call last):
  File "sphinx/events.py", line 96, in emit
    results.append(listener.handler(self.app, *args))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "sphinx_gallery/docs_resolv.py", line 471, in embed_code_links
    _embed_code_links(app, gallery_conf, gallery_dir)
  File "sphinx_gallery/docs_resolv.py", line 324, in _embed_code_links
    doc_resolvers[this_module] = SphinxDocLinkResolver(
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "sphinx_gallery/docs_resolv.py", line 146, in __init__
    if doc_url.startswith(('http://', 'https://')):
       ^^^^^^^^^^^^^^^^^^
AttributeError: 'PosixPath' object has no attribute 'startswith'
```

**Comment by larsoner** [comment]
Nope, but I can open a quick PR for you to test

**Comment by larsoner** [comment]
... actually it looks like that was fixed *before* this PR, so `master` should work already

**Comment by pllim** [comment]
In that case, what is the timeline to release sphinx-gallery?

**Comment by larsoner** [comment]
None at the moment. In theory we should release given the breakages I guess! You can use for example `pip install git+https://github.com/sphinx-gallery/sphinx-gallery.git@309e5be03088410e495c32272edd09cc9548e50c` to work around 7.2 errors for now

**Comment by larsoner** [comment]
@lucyleeow WDYT about cutting a release?

**Comment by pllim** [comment]
I want to avoid pinning our infrastructure to unreleased sphinx-gallery if possible, so I can pin `sphinx<7.2` until a new release is available.

**Comment by pllim** [comment]
Just to report back that using the dev version of sphinx-gallery + sphinx 7.2.2 , I got a green RTD build, so I am looking forward to your release. Thanks!

xref https://github.com/astropy/astropy/pull/15184

**Comment by lucyleeow** [comment]
> @lucyleeow WDYT about cutting a release?

Sorry I don't think I will have time for that. I will fix my PRs though so they get in.

**Comment by pllim** [comment]
From the looks of https://github.com/sphinx-gallery/sphinx-gallery/blob/master/.github/workflows/release.yml , anyone with maintainer access should be able to release?

p.s. You don't need to upload/download artifact unless you are building architecture specific wheels, which I don't think you are.

**Comment by lucyleeow** [comment]
@larsoner I've done some labelling to make release easier for you. Thank you :pray:

**Comment by larsoner** [comment]
I saw that on your PRs, much appreciated :)

I'll look into releasing now, indeed with the `release.yml` I think it's pretty quick I think...

**Pull request merged**
