### PR TITLE
Release 0.8.2

### PR DESCRIPTION
**Pull request by lucyleeow**

### CODE REVIEW

**Comment by lucyleeow** [comment]
Error is because mayavi is failing to build. I think it's related to numpy:

>   Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-req-build-j6_y21f6/setup.py", line 406, in <module>
      raise RuntimeError(msg)
  RuntimeError:
      Numpy is required to build Mayavi correctly, please install it first.
 
and later:

>  creating build/temp.linux-x86_64-3.7/tvtk
    creating build/temp.linux-x86_64-3.7/tvtk/src
    compile options: '-I/home/circleci/.local/lib/python3.7/site-packages/numpy/core/include -I/usr/local/include/python3.7m -c'
    gcc: tvtk/src/array_ext.c
    In file included from /home/circleci/.local/lib/python3.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1822,
                     from /home/circleci/.local/lib/python3.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                     from /home/circleci/.local/lib/python3.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                     from tvtk/src/array_ext.c:223:
    /home/circleci/.local/lib/python3.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
Do we specifically have to pip install numpy first? It doubt this...

**Comment by lucyleeow** [comment]
Locally with python 3.7.7, I also couldn't build wheel for mayavi but using setup.py worked:
```
  DEPRECATION: mayavi was installed using the legacy 'setup.py install' method, because a wheel could not be built for it. pip 21.0 will remove support for this functionality. A possible replacement is to fix the wheel build issue reported above. You can find discussion regarding this at https://github.com/pypa/pip/issues/8368.
```

any ideas @larsoner ?

**Comment by lucyleeow** [comment]
What was the reason for installing mayavi from master?

Locally doing: `pip install numpy vtk` and then `pip install https://github.com/enthought/mayavi/zipball/master` worked. I could amend our circle ci file to do this but I don't why pip was able to install the requirements...?

**Comment by larsoner** [comment]
The real bug is this:
```
    Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.
```
It's usually related to a PyQt5 update. I'll push a commit that should fix it

**Comment by larsoner** [comment]
@lucyleeow I forgot there is a PyQt5 5.15.2 bug where it requires libxcb-util1 but most linuxes have only util0, so for now I just use `!=5.15.2`. I included a bunch of cleanups as well. Feel free to continue and merge when you're happy

**Comment by lucyleeow** [comment]
Thank you, that seems like magic.

**Comment by lucyleeow** [comment]
Just a quick query @larsoner - on circleci we will test python 3.8 and 3.6? Did we want to avoid 3.7..?

**Comment by larsoner** [comment]
>  on circleci we will test python 3.8 and 3.6? Did we want to avoid 3.7..?

On CircleCI we only really "test" (here: build docs fully) on one platform, that was 3.7 but I bumped it up to 3.8. The 3.6 variants IIRC are other non-build jobs like uploading do very little if any Python processing and could in principle be changed to 3.8 as well if we wanted.

**Comment by larsoner** [comment]
I'm going to merge this so that CIs are happy, feel free to continue the release process whenever you're ready @lucyleeow

**Pull request merged**
