### PR TITLE
[MRG] CSS: float the download buttons on wide screens

### PR DESCRIPTION
**Pull request by GaelVaroquaux**
To make them more visible to users for download

### CODE REVIEW

**Comment by GaelVaroquaux** [comment]
Continuation of discussion on #329

**Comment by GaelVaroquaux** [comment]
Links to the rendered pages:
* https://336-25860190-gh.circle-artifacts.com/0/home/ubuntu/sphinx-gallery/alabaster_html/auto_examples/plot_colors.html
* https://336-25860190-gh.circle-artifacts.com/0/home/ubuntu/sphinx-gallery/rtd_html/auto_examples/plot_colors.html

And screenshot with default sphinx theme:
sphx-glr

I think that this is a usability improvement compared to what we have.

**Comment by lesteve** [comment]
Nice! The floating right is a bit weird on the readthedocs theme (which is the one we used in sphinx-gallery.github.io). From [this example](https://336-25860190-gh.circle-artifacts.com/0/home/ubuntu/sphinx-gallery/rtd_html/auto_examples/plot_exp.html#sphx-glr-auto-examples-plot-exp-py):

screenshot-2018-1-8 plotting the exponential function sphinx-gallery 0 1 13-git documentation

**Comment by GaelVaroquaux** [comment]
I don't think that it's that bad. What bother's you? That's it's too far on the right?

**Comment by lesteve** [comment]
> That's it's too far on the right?

Yeah I was wondering if there is an easy way to make it float just a bit right of the example code. If there is no easy way to do that, it's fine with me.

**Comment by GaelVaroquaux** [comment]
> Yeah I was wondering if there is an easy way to make it float just a bit right
> of the example code. If there is no easy way to do that, it's fine with me.

Trying something...

**Comment by GaelVaroquaux** [comment]
OK, I've tried something that should look better (and caught a design bug
in the same time :D).

Tell me how you like it

**Comment by larsoner** [comment]
A bit too late to look at this, but for MNE before #329 we had:

screenshot from 2018-01-08 12-20-29

#329 it broke a bit:

screenshot from 2018-01-08 12-22-12

After this PR (e87efda) it looks just like the above until I make the screen wider, then I get:

screenshot from 2018-01-08 12-28-12

And wider still:

screenshot from 2018-01-08 12-28-26

These problems can be fixed, but it is worth knowing that CSS tweaking can break existing use cases a bit. By customizing our CSS in MNE perhaps we should even expect that upstream changes can do this (maybe we should put it in the docs somewhere if it's not already there?).

This seems to interact nicely when building the SG docs, though -- and thus probably should anywhere CSS is not customized -- so +1 for merge from me.

**Comment by GaelVaroquaux** [comment]
Fixed for RTD theme:
https://341-25860190-gh.circle-artifacts.com/0/home/ubuntu/sphinx-gallery/rtd_html/auto_examples/plot_exp.html

**Comment by GaelVaroquaux** [comment]
@larsoner : +1 adding a note for saying that customizing CSS is a bit dangerous (it will always be, CSS is unfortunately brittle). Where do you suggest that we add it?

The fix on your side will be easy. In addition, it the latest commit, I've added a new class that you can capture in CSS.

**Comment by GaelVaroquaux** [comment]
I've added a note in CHANGES

**Comment by larsoner** [comment]
Also here is a possibly different sort of problem with the float -- it can sit on top of the content. It's clearest in MNE:

screenshot from 2018-01-08 12-35-25

But even happens at some widths with the SG builds:

screenshot from 2018-01-08 12-36-35

As for the doc, I'd put it in the "And some things can be tweaked directly in CSS:" here:

http://sphinx-gallery.readthedocs.io/en/latest/advanced_configuration.html

**Comment by larsoner** [comment]
(I'm still +1 for merge even with this overlap issue, I read that "optimistic merging" article and I figure someone can fix it in a follow-up PR if it's truly irritating)

**Comment by GaelVaroquaux** [comment]
The overlap cannot be fixed. If you think that it is an important problem, we can change the media query so that the behavior switches for larger screens. If people agree that the overlap is a problem they should let me know, and I'll change this behavior.

**Comment by lesteve** [comment]
FWIW in Firefox 57 I see an overlap with the text for readthedocs theme in https://341-25860190-gh.circle-artifacts.com/0/home/ubuntu/sphinx-gallery/rtd_html/auto_examples/plot_exp.html even in full-screen window (even if there is plenty of space on the right)

screenshot-2018-1-8 plotting the exponential function sphinx-gallery 0 1 13-git documentation 1

**Comment by Titan-C** [comment]
@lesteve  I'm on Firefox 57 and I don't see such overlap on a wide screen window. This PR looks nice enough. 
As a side opinion. What if we put this buttons at the head of the document instead of the footer and save ourselves the pain of having a floating element?

**Comment by GaelVaroquaux** [comment]
I'd rather not have the buttons on the top, as they take a lot of
vertical space, and its a problem if users that click to see the example
have to scroll.

I am working on reducing a bit the overlap. Stay tuned.

**Comment by larsoner** [comment]
> What if we put this buttons at the head of the document instead of the footer and save ourselves the pain of having a floating element?

This would be done via changing the ordering of the elements within the HTML template rather than tweaking the CSS, right? If so, -1 on this as it can't be reverted/fixed via CSS.

**Comment by GaelVaroquaux** [comment]
OK, I worked to reduce the overlap. Here is the link to rendered versions:

* RTD theme: https://344-25860190-gh.circle-artifacts.com/0/home/ubuntu/sphinx-gallery/rtd_html/auto_examples/plot_choose_thumbnail.html
* Albany theme: https://344-25860190-gh.circle-artifacts.com/0/home/ubuntu/sphinx-gallery/alabaster_html/auto_examples/plot_choose_thumbnail.html

I hope that this is good to go. It can still generate some overlap, but minor, and I don't think that it is easy to do less.

**Comment by larsoner** [comment]
Here is what I get for a few views:

screenshot from 2018-01-08 15-51-21

screenshot from 2018-01-08 15-48-15

This one gets a scroll bar , maybe Chrome is just being weird?

screenshot from 2018-01-08 15-48-19

I'm +0 on this change because it always makes it easier to download files or launch Binder, but depending on the resolution it can either be helpful or harmful for example readability.

**Comment by GaelVaroquaux** [comment]
Darn the scrollbar is strange. Let me see if I can reproduce this and fix it.

**Comment by GaelVaroquaux** [comment]
OK, new iteration, that should fix the bugs of the previous iteration and remove even more overlap:

https://345-25860190-gh.circle-artifacts.com/0/home/ubuntu/sphinx-gallery/rtd_html/auto_examples/plot_choose_thumbnail.html
https://345-25860190-gh.circle-artifacts.com/0/home/ubuntu/sphinx-gallery/alabaster_html/auto_examples/plot_choose_thumbnail.html

**Comment by GaelVaroquaux** [comment]
And with a tiny extra improvement to please both @larsoner and @lesteve : 

https://346-25860190-gh.circle-artifacts.com/0/home/ubuntu/sphinx-gallery/rtd_html/auto_examples/plot_choose_thumbnail.html
https://346-25860190-gh.circle-artifacts.com/0/home/ubuntu/sphinx-gallery/alabaster_html/auto_examples/plot_choose_thumbnail.html

**Comment by choldgraf** [comment]
I really like this addition, I think having the buttons float to the side definitely makes them more discoverable. +1 for an optimistic merge (though there have been quite a lot of iterations on this one already!) and spot-checking improvements as people have a chance to get to know the new behavior

**Comment by larsoner** [comment]
LGTM +1 for merge

**Comment by lesteve** [comment]
Merging, thanks a lot @GaelVaroquaux !

**Comment by GaelVaroquaux** [comment]
Great! The iterations (ie y'all being demanding bastards like I am)
really helped, IMHO.

**Comment by agramfort** [comment]
sorry to come late here but I feel this is not an ideal decision. it makes you use a full column for just a button -> it leads to a lot of white spaces.

It also forces you to use a wide screen

**Comment by larsoner** [comment]
@agramfort the button actually floats to the right, so it should (hopefully!) only use already-unused white white space, and when you decrease resolution, it should automatically float to the bottom.

**Comment by agramfort** [comment]
at least here
https://6793-1301584-gh.circle-artifacts.com/0/tmp/circle-artifacts.QIpzD23/html/auto_tutorials/plot_receptive_field.html
the button shows up on the title + is half hidden.

maybe it's an MNE pb though

**Comment by larsoner** [comment]
Yes I get this behavior too at some resolutions:

screenshot from 2018-01-17 15-31-58

> maybe it's an MNE pb though

We do use a width that is larger than the SG build defaults. Not sure how common it will be elsewhere.

**Comment by lesteve** [comment]
In full-width, it looks fine for me (Firefox 57 and Chrome). If I start making the window narrower I get something like @larsoner's snapshot. I don't know if there is a better way of doing it.
* can we float the buttons under the header or at the bottom of the window?
* lower tech solution, maybe we can add link before the title of the example that links to the download section at the bottom of the page?

Other suggestions more than welcome !

**Comment by GaelVaroquaux** [comment]
Typography guidelines for readability say that very wide columns are a bad thing. You should limit the column width in the MNE CSS (eg using max-width).

IMHO: yes it's an MNE  problem that should be fixed there. 

⁣Sent from my phone. Please forgive typos and briefness.​

**Comment by larsoner** [comment]
In MNE our width comes from using `sphinx_boostrap_theme`, which sets the column width to 1170px when the width is >= 1200 px, i.e. similar to themes here:

https://bootswatch.com/

So I suspect anyone using `sphinx_boostrap_theme` in conjunction with `sphinx-gallery` will have this problem. 

In any case, at the MNE end we will either modify our column width, or tweak the floating box behavior to jump to the bottom sooner.

**Pull request merged**
