### PR TITLE
[BUG, MRG] fix issue with api usage dict

### PR DESCRIPTION
**Pull request by alexrockhill**
Fixes https://github.com/sphinx-gallery/sphinx-gallery/issues/1024

### CODE REVIEW

**Comment by larsoner** [comment]
I'm inclined to also make this change I suggested in https://github.com/sphinx-gallery/sphinx-gallery/issues/1024#issuecomment-1261295310:

> In the meantime maybe we should change the default to make it not run at all to make it opt-in. Don't want to break people's builds...

Just in case there are other hidden bugs or slowdowns etc., make it opt-in rather than opt-out by default...

**Comment by alexrockhill** [comment]
> I'm inclined to also make this change I suggested in [#1024 (comment)](https://github.com/sphinx-gallery/sphinx-gallery/issues/1024#issuecomment-1261295310):
> 
> > In the meantime maybe we should change the default to make it not run at all to make it opt-in. Don't want to break people's builds...
> 
> Just in case there are other hidden bugs or slowdowns etc., make it opt-in rather than opt-out by default...

Maybe no one will use or know about it then but that's fine, I'll make a follow-up PR as soon as I have a chance.

**Comment by alexrockhill** [comment]
Ok, all fixed, should be good to merge

**Comment by alexrockhill** [comment]
Ok to merge? It would be nice to have the bug closed

**Comment by larsoner** [comment]
Yes, thanks for the reminder @alexrockhill !

**Pull request merged**
