### PR TITLE
ENH Add last cell config

### LINKED ISSUE #605: last_notebook_cell
Could a `last_notebook_cell` option be added much like the `first_notebook_cell` option for adding snippets that we want executed at the end of the downloaded notebook? This would be used to perhaps report on the user's environment with a tool like [`scooby`](https://github.com/banesullivan/scooby):

```py
sphinx_gallery_conf = {
    ...
    'last_notebook_cell': ("# Report on the environment specs\n"
                            "import scooby\n",
                            "scooby.Report()",)
}
```

With something like this, a user could download the example, run it, and encounter an error then immediately share the environment report... I imagine this will be useful for PyVista (`pv.Report`) and `mne-python` (`mne.sys_info()`)

### PR DESCRIPTION
**Pull request by lucyleeow**
closes #605

### CODE REVIEW

**Comment by lucyleeow** [comment]
@larsoner could you explain to me why `gallery_conf['first_notebook_cell'] = first_cell` is needed at the end of:

```
    # Ensure the first cell text is a string if we have it
    first_cell = gallery_conf.get("first_notebook_cell")
    if (not isinstance(first_cell, str)) and (first_cell is not None):
        raise ValueError("The 'first_notebook_cell' parameter must be type str"
                         "or None, found type %s" % type(first_cell))
    gallery_conf['first_notebook_cell'] = first_cell
```

**Comment by larsoner** [comment]
Thanks @lucyleeow

**Comment by lucyleeow** [comment]
Thanks @larsoner !

I'm still confused about `gallery_conf['first_notebook_cell'] = first_cell` after `first_cell = gallery_conf.get("first_notebook_cell")`...? Is it needed?

**Comment by larsoner** [comment]
I looked to respond but didn't see the comment here in the PR so just skipped it (force push maybe?)

I would keep those so that `'first_notebook_cell'` is a valid key, but then later in the code you shouldn't need `.get` on the dict access.

Also we might not even need the `.get` in the first place if the default-filling code does the job of ensuring the key is in the dict.

**Comment by lucyleeow** [comment]
>  would keep those so that `'first_notebook_cell'` is a valid key,

but how would it ensure that it is a valid key? `first_cell` isn't changed. 
`first_cell = gallery_conf.get("first_notebook_cell")` followed by `gallery_conf['first_notebook_cell'] = first_cell` seems circular to me. What am I missing?
```
    # Ensure the first cell text is a string if we have it
    first_cell = gallery_conf.get("first_notebook_cell")
    if (not isinstance(first_cell, str)) and (first_cell is not None):
        raise ValueError("The 'first_notebook_cell' parameter must be type str"
                         "or None, found type %s" % type(first_cell))
    gallery_conf['first_notebook_cell'] = first_cell
```

> Also we might not even need the `.get` in the first place if the default-filling code does the job of ensuring the key is in the dict.

Yes I thought that was redundant/overly cautious. I can remove the `get`?

**Comment by lucyleeow** [comment]
(I mean the `raise ValueError` doesn't change `first_cell`)

**Comment by larsoner** [comment]
You can hopefully remove it both places

**Comment by lucyleeow** [comment]
new PR?

**Comment by larsoner** [comment]
Sure if you want, or we can tackle it later as part of another PR

**Comment by lucyleeow** [comment]
I'll make a new PR! Then we can isolate if it breaks things haha!

**Pull request merged**
