### PR TITLE
MAINT: Modernize requirements

### LINKED ISSUE #192: Lack of `install_requires`
I know `setup.py` notes that not having `install_requires` is a deliberate decision, but is it possible to revisit that decision?

Right now `pip install sphinx-gallery` results in an incomplete install--I still need to manually install sphinx, matplotlib, and pillow to have a functional install. While sphinx and matplotlib are a given for my project, I need to now add `pillow` as a manual install step to my documentation CI builds--and it will break any time dependencies update in the future. Not to mention this becomes a much bigger headache should there be any version-specific needs in the future.

### PR DESCRIPTION
**Pull request by larsoner**
- [x] Adds to the `install_requires` in `setup`
- [x] removes `pytest` from `requirements.txt` (since it's needed for testing, not using SG)
- [x] adds a "minimal" test build with appropriate skips
- [x] removes unnecessary SciPy from `tinybuild`
- [x] removes SciPy from the nightly build (building from source takes > 20 min, all other runs are < 5 min so this is too painful)

Closes #192.

### CODE REVIEW

**Comment by larsoner** [comment]
... and I did not add `mayavi` as an optional thing, since it seems silly to add the capability of `pip install sphinx_gallery[mayavi]` when you can just as easily do `pip install sphinx_gallery mayavi` (seems mostly redundant). But if there are upstream packaging constants then it's simple enough to add.

**Comment by larsoner** [comment]
@Titan-C can you delete `sphinx-gallery` from your AppVeyor account so I can properly set up a `sphinx-gallery` organizational account? That way I (and other admins) can administer the account, kill jobs, etc.

**Comment by larsoner** [comment]
@Titan-C never mind, I was manually able to delete the webhook, create a `sphinx-gallery` account, and reenable the webhook. I'll add the updated badge as part of this PR.

**Comment by GaelVaroquaux** [comment]
LGTM. This a clear improvement.

Merging!

**Pull request merged**
