### PR TITLE
[MRG+1] Add requirements.txt to manifest

### PR DESCRIPTION
**Pull request by ksunden**
Solves the sdist problem with v0.3.0 (see #406)

### CODE REVIEW

**Comment by GaelVaroquaux** [comment]
I believe that this is the right fix. +1 for merge.

And thanks!

**Comment by GaelVaroquaux** [comment]
I'll merge this and try to cut a release in the train (but I only have 15mn, so it's challenging).

**Comment by GaelVaroquaux** [comment]
I've cut a new release. The problem should be fixed. Can you please confirm.

Thanks

**Comment by choldgraf** [comment]
thanks @GaelVaroquaux for helping with this :-)

**Comment by GaelVaroquaux** [comment]
> thanks @GaelVaroquaux for helping with this :-)

Sorry that I cannot be more present. I have so many more things to do
that are more "important" than coding.

**Comment by ksunden** [comment]
Indeed, installs from pypi on my machine

**Pull request merged**
