### PR TITLE
[MRG] ENH: only directive for downloads

### LINKED ISSUE #297: Download button and 'generated by sphinx-gallery' should be only:: html
When generating a PDF with a project using sphinx-gallery, the examples appear with 
"""
Download Python source code:
Download Jupyter notebook:
Generated by Sphinx-Gallery
"""
Which is very strange. We should put the corresponding rst code in "only" directives so that it appears only on html output

### PR DESCRIPTION
**Pull request by GaelVaroquaux**
Fixes #297

### CODE REVIEW

**Comment by larsoner** [comment]
Do we generate any PDFs in the tests / on CircleCI? Perhaps we should. We could maybe add it to the `conf.py` for #296 so we can easily inspect the output, but we'd have to be careful about LaTeX requirements.

**Comment by GaelVaroquaux** [comment]
Adding LateX on Circle will increase the build times a lot. Are we sure that we want to do that?

**Comment by larsoner** [comment]
> Are we sure that we want to do that?

I'll open a PR so we can see how much time/pain it adds :)

**Comment by larsoner** [comment]
When I rebase this on my `intersphinx`, do `make latexpdf`, and view it, I still see the:
```
Download Python source code:
Download Jupyter notebook:
plot_numpy_scipy.py
plot_numpy_scipy.ipynb
Gallery generated by Sphinx-Gallery
```
I don't understand how this is possible given the code. I assume you tested locally and it works for you?

**Comment by larsoner** [comment]
Oh actually it looks like a `make clean` fixes it. +1 for merge from me

**Comment by choldgraf** [comment]
TIL about the `only` directive. neat!

**Comment by GaelVaroquaux** [comment]
> Oh actually it looks like a make clean fixes it. +1 for merge from me

Thanks for checking!

**Pull request merged**
