### PR TITLE
Bump release version

### PR DESCRIPTION
**Pull request by lucyleeow**
Sorry, @larsoner, another question - in the [maintainers](https://sphinx-gallery.github.io/dev/maintainers.html#how-to-make-a-release) doc under 'create a new release on github', I didn't understand what:
```
Make sure to update any links to point to the tag that will be created for this release 
(e.g., change HEAD to v0.3.0).
``` 
was referring to? This link?
```
[Full Changelog](https://github.com/sphinx-gallery/sphinx-gallery/compare/v0.5.0...v0.6.0)
```

### CODE REVIEW

**Comment by GaelVaroquaux** [comment]
I don't fully understand your question @lucyleeow 

With regards to bumping the version number the question is whether we will cut a 0.6.1 release before an 0.7. I don't know what the best practice is. I think that I would put the version number to 0.6.1.dev0, because if we cut an 0.6.1, it will be considered as less recent than 0.7.0dev0, and hence the release will not override old dev code. @larsoner , any opinion?

**Comment by larsoner** [comment]
I would bump the version to `0.7.dev0` and just backport whatever we need to a `0.6.1` if we need to (but for this project we rarely seem to backport anything for `.1` releases, maybe just tiny fixes)

**Comment by larsoner** [comment]
... but in any case, I'm not sure what the HEAD stuff is talking about.

**Comment by lucyleeow** [comment]
I'm going to remove it from the doc - it's just confusing. Thanks everyone!

**Pull request merged**
