### PR TITLE
DOC Add sphinxext opengraph for our doc

### PR DESCRIPTION
**Pull request by lucyleeow**
Related to #707 

Also adds a 'related_projects' page in documentation.

### CODE REVIEW

**Comment by larsoner** [comment]
To me the important change is to make it so that individual rendered examples have OpenGraph information so that they embed nicely. Do you want to try that here, too?

**Comment by lucyleeow** [comment]
> To me the important change is to make it so that individual rendered examples have OpenGraph information so that they embed nicely. 

Did not realise more work was required for that...I guess I will look into that.

**Comment by larsoner** [comment]
Disclaimer: I don't know what is required. Ideally though I think the opengraph for example A would show the scaled or (probably better) original thumbnail image for example A, example B would show example B etc. So the image+link would be example specific and need to know the image URL to show on an example by example basis

**Comment by larsoner** [comment]
Just saw your edits... Yes I mean that when MNE or scikit learn deploys docs a someone embeds a link to example A, the preview that is down should be specific to that example. When they link to example B, the image should be specific to that example, and so on

**Comment by lucyleeow** [comment]
Ah okay I understand now - I was wondering about the image config of opengraph. Yes I agree their implementation could be improved but reading through the thread in #707 it sounded like some work would be required and I am not sure I have the time now. Maybe I should close this and re-think.

**Comment by lucyleeow** [comment]
Of note, I have just seen the `ogp_use_first_image` config:
```
This is not required. Set to True to use each page's first image, if available. If set to True but no image is found, Sphinx will use ogp_image instead.
```

This is not necessarily the thumbnail though.

**Pull request closed without merging**
