### PR TITLE
[MRG] Large codebase refactoring

### PR DESCRIPTION
**Pull request by Titan-C**
This is inspired by the way PR #148 handles the creation of the jupyter notebook, and requires that PR to be merged first. The idea is writing the rst file shall be completely independent of the execution of the script. This PR splits the script execution from the preparation of the RST file

### CODE REVIEW

**Comment by lesteve** [comment]
Looks like this one needs a rebase.

**Comment by Titan-C** [comment]
Merge after #190

**Comment by jnothman** [comment]
My availability atm is very limited, @Titan-C, but I'll see if I can squeeze this in in a few weeks' time.

**Comment by Titan-C** [comment]
Sorry to bother you @jnothman, the review request was an error on my side discovering the github interface for that. This PR I will not rebase anymore. I'll try to redo this changes in new smaller PR.

**Comment by jnothman** [comment]
No worries. Feel free to request reviews if you feel appropriate in any
case! :)

**Pull request closed without merging**
