### PR TITLE
Path class

### PR DESCRIPTION
**Pull request by Titan-C**
This is more of a nice feature to have(mostly inspired by the work done in plot2rst). But that I could test and allowed me to discover the bug fixed in #34 . It extends the string class for paths, given some ease of use when working with paths.

### CODE REVIEW

**Comment by lesteve** [comment]
@Titan-C, is that still something we want?

**Comment by GaelVaroquaux** [comment]
> @Titan-C, is that still something we want?

What is it actually? I didn't get it from the description of the PR.

**Comment by lesteve** [comment]
Not entirely sure, but it looks like adding a Path class for more convenient path manipulations ...

**Comment by Titan-C** [comment]
> What is it actually? I didn't get it from the description of the PR.

Can't really explain it better.
- It's an internal feature, not for the user. It was inspired by the fact that the gallery has to deal with multiple paths(examples_source_dir, Gallely_dir, modules_dir, file_path, image_paths, ...)
- The idea is to store this paths not only as strings, but in an object that is aware they are paths and provide inherent features of this. Like, joining paths, creating dir, listing dirs, checking it the path exists or is a directory.

It remains a nice feature to have which I was very eager to use, back when #36 was only aimed at refactoring the code. Now it needs an update from master.

**Comment by GaelVaroquaux** [comment]
I always frown at adding abstractions, because abstractions make life
easier for their creators, and harder for people who have to discover
them.

If you really want to go down that path (sic), you can use the
semi-standard 'path.py' existing Python package:
https://pypi.python.org/pypi/path.py

For this, you'll need a to embed a version, and thus add a note to the
license.

**Comment by Titan-C** [comment]
No more need for this anymore.

**Pull request closed without merging**
