### PR TITLE
plot sorted running time of examples when building the doc

### PR DESCRIPTION
**Pull request by agramfort**
cc @jaeilepp 

that's useful in mne-python to tracking the examples that take the most time.

@Titan-C feel free to take over to make it at your taste

### CODE REVIEW

**Comment by agramfort** [comment]
@lesteve @Titan-C any objection?

**Comment by agramfort** [comment]
@GaelVaroquaux gave its +1 IRL :)

**Comment by GaelVaroquaux** [comment]
+1

**Comment by Titan-C** [comment]
It looks fine. I would also ask to write about it on the Changes.rst

I'm also thinking. What if you accumulate the computation time in the same list, where the amount of code is? Maybe we can use it in the future to sort the examples by build time?

**Comment by agramfort** [comment]
>
> It looks fine. I would also ask to write about it on the Changes.rst
>
 pushed. Take over if it's not the way you see it.

> I'm also thinking. What if you accumulate the computation time in the same
> list, where the amount of code is? Maybe we can use it in the future to
> sort the examples by build time?
>
it feels a bit YAGNI to me.

**Comment by Titan-C** [comment]
This needs a rebase

**Comment by agramfort** [comment]
done

**Pull request merged**
