### PR TITLE
MRG: Add timing information

### LINKED ISSUE #203: Add a page showing the time taken by the examples
It would be good to have an html page in the rendered output that shows the time taken by the examples (absolute and relative), probably ordered. It would help controlling that. It is mostly a developer tool, so we should make it very discreet, probably accessible via a very light link at the bottom of the gallery.

### PR DESCRIPTION
**Pull request by larsoner**
Closes #203.

Todo:

- [x] Add total computation time at the top
- [x] Make it prettier (table?)

### CODE REVIEW

**Comment by larsoner** [comment]
@GaelVaroquaux I think this is what you were asking for in #203 (I agree it would be useful in MNE). Feel free to take over to tweak the ReST to taste if you have time (you can push directly to my branch assuming you can as a SG maintainer), or comment here and I can do it. This is what it looks like:

https://370-25860190-gh.circle-artifacts.com/0/home/ubuntu/sphinx-gallery/doc/_build/html/auto_examples/sg_execution_times.html

It's not the most beautiful thing in the world -- maybe it should be a table. It should probably also show the total computation time, now that I think about it.

I haven't linked to it from examples or anywhere else because I consider this summary a "maintainer tool" more than something users would be interested in, given that they can see per-example timings already.

**Comment by larsoner** [comment]
Let's just get this one in and we can make it prettier later. It's mostly an advanced option for devs anyway. There is now a link to it in the configuration page to note its existence. For us it looks pretty trivial:

https://635-25860190-gh.circle-artifacts.com/0/html/auto_examples/sg_execution_times.html#sphx-glr-auto-examples-sg-execution-times

Should be ready for merge for 0.3.

**Comment by choldgraf** [comment]
LGTM - that's a nifty feature!

**Comment by larsoner** [comment]
Tweaked to include total for the directory

https://646-25860190-gh.circle-artifacts.com/0/html/auto_examples/sg_execution_times.html

@choldgraf feel free to merge if you are happy

**Comment by choldgraf** [comment]
cool - nice patch! 🎉

**Pull request merged**
