### PR TITLE
ENH: Support linking to builtin modules

### PR DESCRIPTION
**Pull request by larsoner**

### CODE REVIEW

**Comment by larsoner** [comment]
See for example `sys.argv` gets linked properly [by this PR](https://1100-25860190-gh.circle-artifacts.com/0/rtd_html/auto_examples/plot_sys_argv.html) but not [by master](https://sphinx-gallery.github.io/auto_examples/plot_sys_argv.html).

**Comment by larsoner** [comment]
Travis is happy, no idea why it says it's pending.

@choldgraf or @lucyleeow feel free to review

**Comment by choldgraf** [comment]
Ah cool - this seems pretty reasonable to me! Looks good + test looks good as well, so let's 🚢 it!

**Comment by NicolasHug** [comment]
Is there an option to deactivate linking to external libraries? I think that this PR is causing https://github.com/scikit-learn/scikit-learn/issues/15812 in scikit-learn, where too many links are generated by in the gallery examples


See for example [0.22](https://scikit-learn.org/stable/auto_examples/tree/plot_unveil_tree_structure.html) vs [0.21](https://scikit-learn.org/0.21/auto_examples/tree/plot_unveil_tree_structure.html)

**Comment by NicolasHug** [comment]
Ignore my comment, that's actually unrelated, sorry for the noise!

**Pull request merged**
