### PR TITLE
MRG: Use highlight_language

### LINKED ISSUE #452: SG not respecting highlight_lang in conf.py
If I specify `highlight_language = 'python3'` in my `conf.py`, sphinx-gallery nonetheless outputs code blocks starting with:
```
.. code-block:: python
```
...presumably because of [default `lang=python` arg in `codestr2rst`](https://github.com/sphinx-gallery/sphinx-gallery/blob/40aec52de43e4c27b000e054ae50eae6fb0f30e2/sphinx_gallery/gen_rst.py#L178).  This leads to errors where plain RST files get lexed as python3, but the gallery files get lexed as python2 (which chokes on the `@` operator), as evidenced by these two errors:
```
/opt/mne-python/doc/auto_tutorials/preprocessing/working_with_projectors.rst:48: WARNING: Could not lex literal_block as "python". Highlighting skipped.
/opt/mne-python/doc/manual/gui/browse.rst:2533: WARNING: Could not lex literal_block as "python3". Highlighting skipped.
```
(note: the second is an intentional error that I left in manual/gui/browse.rst to demonstrate that it is being lexed as py3, unlike the SG-generated rst files)

### PR DESCRIPTION
**Pull request by larsoner**
Closes #452.

### CODE REVIEW

**Comment by drammock** [comment]
confirmed; SG on branch `larsoner:language` highlights as py3 when `conf.py` contains `highlight_language = 'python3'`

**Comment by drammock** [comment]
thanks @larsoner

**Comment by larsoner** [comment]
@choldgraf this one is good to go, too :)

**Comment by choldgraf** [comment]
@larsoner you are on a roll!!! Thanks for this patch, it looks good to me 🎉

**Pull request merged**
