### PR TITLE
syntax error fix in sphinx_gallery.downloads

### PR DESCRIPTION
**Pull request by photoniker**
some syntax error in the member downloads.CODE_DOWNLOAD and downloads.CODE_ZIP_DOWNLOAD which were not interpretate right in the resulting *.rst file.

### CODE REVIEW

**Comment by lucyleeow** [comment]
Can you provide more details of the error you are getting?

**Comment by photoniker** [comment]
Hi, I did not get directly an error. I saw that syntax error for the `.. only :: ` command where the whitespace character must deleted otherwise it is wrong in the *.rst file. 

I can show the differences based on some auto generated *.rst files by using the sublime text editor for syntax highlighting. 

- `.. only :: html`
image


- `.. only:: html`
image

**Comment by lucyleeow** [comment]
I'm reluctant to change our code just based on an editors syntax highlighting, esp if the html renders fine?

**Comment by photoniker** [comment]
Understandable, I had that once that then the '*.rst' was not rendered correctly. 
In 'sphinx_gallery.gen_rst.EXAMPLE_HEADER' it is also correct with ` .. only::`. 

It's just a request ;-) @

**Comment by photoniker** [comment]
OK great this was my request for ;-)

**Comment by larsoner** [comment]
Thanks @photoniker !

**Pull request merged**
