### PR TITLE
Start changelog fix #67

### LINKED ISSUE #67: Add whats_new/CHANGES file
to list main changes in new releases.

From #66:

> Do a CHANGES.txt file and 'include' it somewhere in the docs. You can see how joblib does it for instance.

Maybe we want to do something similar as scikit-learn/nilearn and have a doc/whats_new.rst + include the rst in the doc somewhere.

### PR DESCRIPTION
**Pull request by Titan-C**
I stated doing the changelog manually until I found this amazing tool to summarize and link all the changes in the github hosted codebase.

https://github.com/skywinder/Github-Changelog-Generator

### CODE REVIEW

**Comment by lesteve** [comment]
Interesting tool. To be perfectly honest, I reckon it is a bit overkill, especially given the reasonably small size of sphinx-gallery. If scikit-learn can do it by hand, there is no strong reason sphinx-gallery can not do the same.

**Comment by GaelVaroquaux** [comment]
> Interesting tool. To be perfectly honest, I reckon it is a bit
> overkill, especially given the reasonably small size of sphinx-gallery.
> If scikit-learn can do it by hand, there is no strong reason
> sphinx-gallery can not do the same.

+1

**Comment by Titan-C** [comment]
It is an overkill indeed and it misses some extra comments on the features added. I have kept the skeleton of it for the old changes. Then added some manual work to put more text to the last release. Highlighting the notebook styled examples and changing the module name. After this, I think, I can continue with a manual update of changes.

**Comment by lesteve** [comment]
Closing this one since everybody seem to agree that we don't need it.

**Pull request closed without merging**
