### PR TITLE
Fix #288, Gallery branding

### LINKED ISSUE #288: "Generated by sphinx-gallery" should be replaced by "Gallery generated by sphinx-gallery"
In a gallery, it would be better to write "Gallery generated by sphinx-gallery", as when the gallery is included somewhere, it looks weird.

### PR DESCRIPTION
**Pull request by Titan-C**

### CODE REVIEW

**Comment by GaelVaroquaux** [comment]
Thank you! That was fast! Merging.

FYI: I am currently renewing the scipy intro chapter of the scipy-lectures. I am integrating sphinx-gallery to it, and I really like the way that I can add a gallery of examples / exercices at the end:
http://gael-varoquaux.info/scipy-lecture-notes/intro/scipy.html#full-code-examples-for-the-scipy-chapter

**Comment by choldgraf** [comment]
@GaelVaroquaux do you have a link the branch you're using for that? I'm curious to see the code you're using to generate the gallery in this way.

Also, for these kinds of things, I think it'd be helpful if we had a section of the docs that pointed to "good" examples of the use of sphinx gallery

**Comment by GaelVaroquaux** [comment]
> @GaelVaroquaux do you have a link the branch you're using for that?

It's:
https://github.com/GaelVaroquaux/scipy-lecture-notes/tree/renew_scipy

> Also, for these kinds of things, I think it'd be helpful if we had a
> section of the docs that pointed to "good" examples of the use of
> sphinx gallery

That would certainly be a good thing, though I am afraid that this might
still be something that we are learning.

**Comment by choldgraf** [comment]
thx, cool!

**Pull request merged**
