### PR TITLE
ENH: New file-based conf-parameter thumbnail_path

### PR DESCRIPTION
**Pull request by prisae**
Adds the possibility to use an arbitrary image as thumbnail on a per-file basis by providing the path, e.g.,
```
# sphinx_gallery_thumbnail_path = '_static/yourimage.png'
```

Addresses #607

### CODE REVIEW

**Comment by larsoner** [comment]
To test this I would make some change to an example in `sphinx_gallery/tests/tinybuild` and then assert that the `<img` HTML tag shows up properly somewhere in a `sphinx_gallery/tests/test_full.py` test (maybe a new one reusing a fixture or just in an existing one)

**Comment by prisae** [comment]
I added it to the docs and as additional example. I also replicated the test for `thumbnail_number`. However, I am not sure if this is enough. But I am not sure I understood your input regarding the tests...

Also, the tests seem to fail, but not sure if it is actually related to this PR.

**Comment by larsoner** [comment]
@prisae pushed a commit with a variant of the test I was talking about (plus some fixes to get some other tests happy again). See if you're happy. If so I'll take a look at the documentation and hopefully merge!

**Comment by prisae** [comment]
I just tested it on my local gallery, and it works all fine with your changes, so LGTM if you think this implementation is stable enough. The only thing I was unsure is about the path, relative to what. I chose relative to `gallery_conf['src_dir']`, I guess that is OK.

Thanks for your help @larsoner !

**Comment by larsoner** [comment]
Yes I think that's the sensible choice. And given that things are green here and not on `master` let's go ahead and merge. @lucyleeow feel free to look and comment if you have time and we can always do a follow-up PR

**Pull request merged**
