### PR TITLE
[MRG] Use static.mybinder.org for badge image

### PR DESCRIPTION
**Pull request by yuvipanda**
This prevents cookies used in mybinder.org from being sent 
when requesting the badge, enhancing privacy.

https://github.com/jupyterhub/binderhub/issues/379 for original
issue about this.

### CODE REVIEW

**Comment by Titan-C** [comment]
This does not seem to fix the issue with privacy badger thinking there is tracking going on from the domain static.mybinder.org
In our circle CI build privacy badger still says there is a potential tracker.
https://333-25860190-gh.circle-artifacts.com/0/home/ubuntu/sphinx-gallery/rtd_html/auto_examples/plot_seaborn.html#sphx-glr-auto-examples-plot-seaborn-py

**Comment by yuvipanda** [comment]
@Titan-C can you restart the CI build and check now? We discovered that Google Analytics defaults to setting cookies for all subdomains, and have deployed a fix now.

**Comment by GaelVaroquaux** [comment]
I cannot anymore, because there are conflicts.

The easiest solution is that you rebase on master, and solve the conflicts. This will restart CI.

**Comment by yuvipanda** [comment]
Looks like I had another conflict, but I think CircleCI passed and our latest patch upstream has fixed the privacy issue. Will wait for this one to pass too...

**Comment by yuvipanda** [comment]
(am happy to rebase+squash after this passes if you want a cleaner history)

**Comment by yuvipanda** [comment]
w00t, it passed!

**Comment by lesteve** [comment]
@Titan-C can you check that it makes you privacy badger extension happy?

**Comment by Titan-C** [comment]
My privacy badger seems to have blacklisted mybinder.org and
static.mybinder.org as trackers. But using a new/clean profile in
Firefox with the extension newly installed does fix the issue and
static.mybinder.org is not a tracker anymore.

This issue is solved for me.

I'll open an issue with privacy badger to request a refresh policy when
domains are not tracking anymore.

**Comment by lesteve** [comment]
Thanks a lot merging!

**Comment by yuvipanda** [comment]
Thank you very much for noticing, reporting and then merging our fixes! Glad there are still lots of communities that take privacy seriously! <3 🎆

**Pull request merged**
