### PR TITLE
Fix broken links when using dirhtml builder

### PR DESCRIPTION
**Pull request by mgoulao**
The idea of this PR is to develop a better solution to #921.

* Remove `dirhtml` blocking and associated test
* Add condition to `directives.visit_imgsg_html` to support `dirhtml` special case

I'm unaware of any other problem related to using the `dirhtml` builder.

### CODE REVIEW

**Comment by larsoner** [comment]
> I'm unaware of any other problem related to using the dirhtml builder.

I think in order to un-block it like this we need to test it to make sure it succeeds without error. The easiest way to add such a test would probably be to run the `tinybuild` HTML build using the `dirhtml` builder.

**Comment by mgoulao** [comment]
I have added a simple `test_error_messages_dirhtml` test which passed. Is this enough? Or should I duplicate every test using the `sphinx_app` fixture?

**Comment by larsoner** [comment]
> Or should I duplicate every test using the sphinx_app fixture?

No I don't think that's necessary. I'll try to push a commit to make CIs happy, at the very least CircleCI is protecting against unregistered/new users...

**Comment by larsoner** [comment]
All green after a few style fixes and making the code more DRY, thanks @mgoulao !

**Pull request merged**
