### PR TITLE
[MRG+1] FIX: Update packages

### PR DESCRIPTION
**Pull request by larsoner**
Let's see if CircleCI is happy with this.

### CODE REVIEW

**Comment by larsoner** [comment]
CircleCI is happy:

https://circleci.com/gh/sphinx-gallery/sphinx-gallery/225#artifacts/containers/0

**Comment by choldgraf** [comment]
Is there a concern that this will randomly break at some point in the future if a package gets updated?

**Comment by GaelVaroquaux** [comment]
If it breaks when a package is updated, it is quite a good thing: it will make explicit a breakage that would have happened on users computer.

+1 for merge

**Comment by lesteve** [comment]
LGTM, merging, thanks a lot!

**Pull request merged**
