### PR TITLE
ENH: Use broader def of Animation

### PR DESCRIPTION
**Pull request by larsoner**
Matplotlib also has `ArtistAnimation`. It would be nice to have this for matplotlib (https://github.com/matplotlib/matplotlib/pull/17477), maybe in a 0.7.1 release sometime? Let's wait to see what else breaks in the meantime before cutting one, though.

### CODE REVIEW

**Comment by lucyleeow** [comment]
@larsoner how did you know the error:

> Exception occurred:
  File "/home/circleci/.local/lib/python3.7/site-packages/sphinx/setup_command.py", line 196, in run
    'caused by %s builder.' % app.builder.name)
distutils.errors.DistutilsExecError: caused by html builder.
The full traceback has been saved in /tmp/sphinx-err-q_gjzrqx.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!

was caused by optipng? That error message is a bit cryptic.

**Comment by larsoner** [comment]
Warnings are treated as errors, I ctrl-F'ed "warning" in the doc build log and found the warning

**Comment by lucyleeow** [comment]
I see the `-W` is doing that in `python setup.py build_sphinx -nW --keep-going` but what does the exception above mean? Does it just mean that there was a warning somewhere?

**Comment by larsoner** [comment]
> Does it just mean that there was a warning somewhere?

Yeah. Newer sphinx is supposed to tell you that there was a warning that was treated as an error that killed the build but apparently it didn't work in this case

**Comment by lucyleeow** [comment]
Ah right. Thanks!

**Pull request merged**
