### PR TITLE
[MRG]: MISC: CSS: fix predecence

### PR DESCRIPTION
**Pull request by GaelVaroquaux**
Fix a bug in my previous layout (minor one, but this fix reduces screen
real estate used by download buttons).

### CODE REVIEW

**Comment by GaelVaroquaux** [comment]
To ease review, here are the rendered versions:
https://350-25860190-gh.circle-artifacts.com/0/home/ubuntu/sphinx-gallery/rtd_html/auto_examples/plot_choose_thumbnail.html
https://350-25860190-gh.circle-artifacts.com/0/home/ubuntu/sphinx-gallery/alabaster_html/auto_examples/plot_choose_thumbnail.html

I know, the difference is very small: it's a .5ex difference on the side of the buttons. But on both sides, 2 x .5ex = 1ex, and that's one extra character less of overlay (@lesteve got me picky about overlay)

**Comment by lesteve** [comment]
:confused: have you changed something other than moving things around?

**Comment by GaelVaroquaux** [comment]
> 😕 have you changed something other than moving things around?

No. But a rule setting the padding of the floating div to .5ex was
overridden because the "media" block was too high up. This is why I
moved it down. Hence the actual rendered CSS did change by 2 x .5ex when
the div is floating.

**Comment by lesteve** [comment]
Just for completeness what I mean is: if you realign the diff then nothing has changed in your CSS ...

**Comment by lesteve** [comment]
Ah ... some CSS subtleties that maybe one day I will learn. OK fair enough, merging, thanks a lot!

**Comment by GaelVaroquaux** [comment]
> Just for completeness what I mean is: if you realign the diff then
> nothing has changed in your CSS ...

Yes, but order matters in CSS: the last rule wins. And given that rules
have different scoping applications, order is actually semantic, and
not a bug.

**Comment by Titan-C** [comment]
> Yes, but order matters in CSS: the last rule wins. 

I was not aware of this. Maybe that's the reason it's always a pain to get CSS working. I usually end setting up a more specialized class or id. It never occurred to me that order in the file was important.

**Pull request merged**
