### PR TITLE
Allow and use https links where possible

### PR DESCRIPTION
**Pull request by QuLogic**
Check for both `http:` and `https:` where necessary, and then use secure links in as many places as possible.

### CODE REVIEW

**Comment by lesteve** [comment]
LGTM.

**Comment by Titan-C** [comment]
Links over functions are not being recognized in python 2. See for example our Circle-CI build
https://107-25860190-gh.circle-artifacts.com/0/home/ubuntu/sphinx-gallery/rtd_html/auto_examples/plot_colors.html

**Comment by Titan-C** [comment]
The links on source code not working in python 2 was introduced in #257. I'm reverting that

**Comment by dopplershift** [comment]
Fixes #236.

**Comment by QuLogic** [comment]
Rebased against latest `master`.

**Comment by Titan-C** [comment]
LGTM. Links are back and using https.
Thank you. I'm merging this.

**Pull request merged**
