### PR TITLE
Introduction tooltip corresponds to the first paragraph

### PR DESCRIPTION
**Pull request by fgmacedo**
Closes: #1066 (related to #1085).

- [x] Introduction tooltip corresponds to the first paragraph and is no longer truncated.
- [x] Tooltip representation is handled using CSS.

#### Without adjusting the `padding`, I got this:

image

Note that given the padding was `10px 10px 10px 10px`, the bottom exposes the top content of the next truncated line:

image

#### Adjusting the `padding`, I got this:

image

### With full default CSS

I've adjusted the clamp to 6 lines, so longer texts use full space, and smaller ones are automatically reduced (states forced to :hover):

image

### CODE REVIEW

**Review by lucyleeow — COMMENTED** [review]
I don't love adding another configuration but if it is not achievable via CSS this seems reasonable.
I'll let @larsoner merge.

**Comment by larsoner** [comment]
> if it is not achievable via CSS this seems reasonable

I think this is probably what we want, and looks like FireFox added support in 2019 so probably okay to use nowadays:

https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-line-clamp#truncating_a_paragraph

It's a bigger PR but in principle then people can just override the number of lines, box width, etc. to their liking rather than us having some artificial character limit.

@lucyleeow do you agree it's a better way forward? If so then @fgmacedo would you be up for trying this?

**Comment by drammock** [comment]
`height` and `padding` are going to play a role here. Probably for the CSS approach to work and still look good, the semitransparent overlay will need to be a separate node from the tooltip text container. By hacking in the browser console like this:

Screenshot_2024-07-09_16-37-43


I can get this:

Screenshot 2024-07-09 at 16-37-23 Basics Gallery with Matplotlib — Sphinx-Gallery 0 17 dev0-git documentation

**Comment by lucyleeow** [comment]
> @lucyleeow do you agree it's a better way forward? 

100% prefer CSS option. We don't want another config.

**Comment by fgmacedo** [comment]
Changing the approach:

1. Introduction tooltip corresponds to the first paragraph and is no longer truncated.
2. Tooltip representation is handled using CSS.

Do you agree with this?

**Comment by larsoner** [comment]
Yes that sounds good!

Looks like there is a tiny visual regression in [this PR](https://output.circle-artifacts.com/output/job/77c0dec4-3193-4ebb-b365-1404cd55c58e/artifacts/0/html/auto_examples/index.html#general-examples) where the mouseover "black box" doesn't cover the whole tile, for example mousing over I see

image

Whereas on [latest dev](https://sphinx-gallery.github.io/dev/auto_examples/index.html#general-examples) I see:

image

Not sure if it's fixable or not...? One solution would be to make one div with `height=100%` that covers the whole tile, and then inside that the next `div` (or whatever) that does the text trucncation.

**Comment by drammock** [comment]
> One solution would be to make one div with `height=100%` that covers the whole tile, and then inside that the next `div` (or whatever) that does the text trucncation.

That's exactly what I was trying to suggest above  when I said

> the semitransparent overlay will need to be a separate node from the tooltip text container

But @larsoner has said it much more clearly :)

**Comment by fgmacedo** [comment]
Still working on this... the last commit I've added the black box as `before` element, but added a regression that the text is leaking the box... not work as expected. 🙈 

image

**Comment by fgmacedo** [comment]
Tests passing locally. Is `sphinx_gallery/tests/test_full.py::test_interactive_example_logo_exists` an intermittent test?

**Comment by lucyleeow** [comment]
real but unrelated to this PR. Its present in #1346 as well.

**Comment by fgmacedo** [comment]
I've currently set the default to 4 lines, but I might have been a bit conservative. How about increasing it to 6 lines?

image

Preview:

https://output.circle-artifacts.com/output/job/1d60ae2a-9e1f-421d-bcf5-3d55c8cb487e/artifacts/0/html/auto_examples/index.html

**Comment by larsoner** [comment]
Failure in sphinx dev was due to https://github.com/sphinx-doc/sphinx/pull/12425 and I pushed a commit to #1346. Once that lands I'll merge `master` into this PR which should get things green, and I'll look at the examples. Agreed 6 is probably better than 4 for line clamping

**Comment by larsoner** [comment]
Rendered doc looks good and locally I tested it on MNE-Python and things looked good so in it goes, thanks @fgmacedo !

**Pull request merged**
