### PR TITLE
Add dedicated class for timing related block

### PR DESCRIPTION
**Pull request by ThomasG77**
This PR is for addressing the need to style timing block by adding a CSS class `sphx-glr-timing` class to `<p>`.

### CODE REVIEW

**Comment by Titan-C** [comment]
I like that this part of the rst document moves to the variable `TIMING_CONTENT`. Can we have a little test for this? The reason I ask is to have something to remember me to port this in PR #239, a test that fails because the class is not found is a great way to remember this was added and does not get lost in all the reordering I do in PR #239

**Comment by larsoner** [comment]
One way to test would be to look at the `tinybuild` HTML output for the proper class name using a regular expression.

**Comment by larsoner** [comment]
@ThomasG77 can you add the test? If not I can probably take over and do it, would be good to get this into the 0.3 release

**Comment by larsoner** [comment]
I rebased, added tests, and force pushed. Since @Titan-C was +1 for merge I'll merge once CIs are green

**Comment by larsoner** [comment]
Passes other than the failure in `master` fixed by #432

**Comment by larsoner** [comment]
Thanks @ThomasG77

**Pull request merged**
