### PR TITLE
[MRG] Changelog regarding nested sections

### PR DESCRIPTION
**Pull request by alexisthual**
Related to #904 , adds short changelog explaining toctree modification.

### CODE REVIEW

**Comment by alexisthual** [comment]
@larsoner @GaelVaroquaux do you think this is clear enough a warning? The changelog bullet feels long already

**Review by larsoner — APPROVED** [review]
+1 for merge

**Comment by alexisthual** [comment]
Great!

**Comment by larsoner** [comment]
Thanks @alexisthual !

**Pull request merged**
