### PR TITLE
ENH: Show memory usage, too

### LINKED ISSUE #522: Show memory usage in build output
The `show_memory` option is cumbersome to work with - I want to see which examples have high memory consumption and I do not want to look through each page in the gallery to find out the memory usage. 

Can you all output the memory usage in the build output similar to how execution times are shown and perhaps sort them from high to low useage?

It'd be nice if the output was formatted more clearly into a raw text table. Maybe something like:

```txt
example execution summary:
            Filename                        Time        Memory
    - ../examples/02-plot/orbit.py         39 sec       282 MB
    - ../examples/02-plot/opacity.py       22 sec       250 MB
    - ../examples/02-plot/lighting.py      21 sec       300 MB
    - ../examples/02-plot/texture.py       20 sec       133 MB
    - ../examples/01-filter/slicing.py     19 sec        85 MB
```

-----

Also, every so often I run into an issue with zombie threads - anyone else experience ths when using `'show_memory': True`:

```zsh
(dev) ➜  docs git:(patch/subplot) ✗ rm -r examples
(dev) ➜  docs git:(master) ✗ make html
Running Sphinx v2.1.2
Adding copy buttons to code blocks...
loading pickled environment... done
generating gallery...

Exception occurred:
  File "/Users/bane/.local/lib/python3.7/site-packages/psutil/_psosx.py", line 370, in catch_zombie
    raise ZombieProcess(proc.pid, proc._name, proc._ppid)
psutil.ZombieProcess: psutil.ZombieProcess process still exists but it's a zombie (pid=71575)
The full traceback has been saved in /var/folders/2x/4df66vz13pv4hj_ysv23tyyc0000gn/T/sphinx-err-8aw1_qos.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [html] Error 2
```

### PR DESCRIPTION
**Pull request by larsoner**
Closes #522.

@banesullivan feel free to try it and open a PR into my branch with any aesthetic tweaks you want (e.g., a header).

### CODE REVIEW

**Comment by larsoner** [comment]
Example output currently, for `tinybuild`:
```
computation time summary:
    - examples/plot_svg.py:                     0.18 sec   11.2 MB
    - examples/plot_numpy_matplotlib.py:        0.18 sec    9.6 MB
    - examples/plot_future_imports.py:          0.11 sec    9.4 MB
    - examples/plot_second_future_imports.py:   0.08 sec    9.4 MB
    - examples/plot_future_imports_broken.py:   0.06 sec    9.4 MB
    - examples/local_module.py:                 0.00 sec    0.0 MB
```
and for SG:
```
computation time summary:
    - ../tutorials/seaborn/plot_seaborn_notebook.py:       48.32 sec    11.7 MB
    - ../examples/plot_seaborn.py:                         22.96 sec    59.0 MB
    - ../tutorials/plot_notebook.py:                        2.39 sec    14.3 MB
    - ../mayavi_examples/plot_3d.py:                        1.88 sec   114.1 MB
    - ../examples/plot_quantum.py:                          1.03 sec     9.4 MB
    - ../examples/plot_function_identifier.py:              0.92 sec     9.5 MB
    - ../examples/plot_colors.py:                           0.83 sec    25.4 MB
    - ../examples/plot_unicode_everywhere.py:               0.74 sec     9.5 MB
    - ../tutorials/plot_parse.py:                           0.64 sec     9.4 MB
    - ../examples/sin_func/plot_sin_black_background.py:    0.46 sec     9.4 MB
    - ../examples/plot_choose_thumbnail.py:                 0.43 sec     9.4 MB
    - ../examples/no_output/plot_raise.py:                  0.41 sec     9.4 MB
    - ../examples/plot_exp.py:                              0.38 sec     9.4 MB
    - ../examples/plot_gallery_version.py:                  0.33 sec     9.5 MB
    - ../examples/sin_func/plot_sin.py:                     0.31 sec     9.4 MB
    - ../examples/no_output/plot_strings.py:                0.26 sec     9.5 MB
    - ../examples/no_output/plot_syntaxerror.py:            0.16 sec     9.4 MB
    - ../examples/plot_sys_argv.py:                         0.14 sec     9.4 MB
    - ../examples/local_module.py:                          0.00 sec     0.0 MB
    - ../examples/no_output/just_code.py:                   0.00 sec     0.0 MB

```
And the HTML file, courtesy CircleCI:

https://969-25860190-gh.circle-artifacts.com/0/rtd_html/auto_examples/sg_execution_times.html

Looks like AppVeyor is broken on `master` and failing on this PR, will probably try to fix that mess separately.

**Comment by larsoner** [comment]
@choldgraf this one should be good to go. We can improve aesthetics in subsequent PRs if people are motivated, but they are already a nice upgrade.

**Comment by choldgraf** [comment]
@banesullivan have you given this one a chance?

**Comment by larsoner** [comment]
Here is the output on [CircleCI for MNE](https://circleci.com/gh/mne-tools/mne-python/14606#artifacts/containers/0):
<details>

    - ../examples/time_frequency/plot_source_power_spectrum_opm.py:                                    158.79 sec   2103.6 MB
    - ../tutorials/source-modeling/plot_mne_solutions.py:                                              129.81 sec    434.4 MB
    - ../examples/inverse/plot_covariance_whitening_dspm.py:                                            94.78 sec   1040.6 MB
    - ../tutorials/source-modeling/plot_forward.py:                                                     91.85 sec   1135.5 MB
    - ../examples/visualization/plot_montage.py:                                                        74.03 sec    309.8 MB
    - ../tutorials/sample-datasets/plot_brainstorm_auditory.py:                                         65.71 sec    529.9 MB
    - ../tutorials/source-modeling/plot_mne_dspm_source_localization.py:                                63.07 sec    114.6 MB
    - ../examples/connectivity/plot_mne_inverse_envelope_correlation.py:                                60.42 sec    749.7 MB
    - ../examples/inverse/plot_mixed_source_space_inverse.py:                                           49.15 sec   1347.9 MB
    - ../examples/connectivity/plot_mixed_source_space_connectivity.py:                                 47.82 sec   1002.0 MB
    - ../tutorials/stats-source-space/plot_stats_cluster_spatio_temporal_2samp.py:                      46.45 sec      8.6 MB
    - ../examples/forward/plot_source_space_morphing.py:                                                46.43 sec    581.5 MB
    - ../examples/visualization/plot_make_report.py:                                                    45.16 sec    663.9 MB
    - ../examples/time_frequency/plot_time_frequency_global_field_power.py:                             45.12 sec   1519.0 MB
    - ../tutorials/source-modeling/plot_eeg_no_mri.py:                                                  44.42 sec    441.5 MB
    - ../examples/inverse/plot_dics_source_power.py:                                                    43.77 sec    453.0 MB
    - ../tutorials/source-modeling/plot_dipole_orientations.py:                                         41.44 sec    454.2 MB
    - ../tutorials/stats-source-space/plot_stats_cluster_spatio_temporal_repeated_measures_anova.py:    41.19 sec      8.3 MB
    - ../tutorials/simulation/plot_dics.py:                                                             40.32 sec     79.8 MB
    - ../tutorials/intro/plot_10_overview.py:                                                           39.86 sec    563.0 MB
    - ../examples/preprocessing/plot_run_ica.py:                                                        39.72 sec    457.9 MB
    - ../tutorials/preprocessing/plot_40_artifact_correction_ica.py:                                    38.74 sec    774.8 MB
    - ../tutorials/simulation/plot_point_spread.py:                                                     38.16 sec    441.9 MB
    - ../examples/connectivity/plot_mne_inverse_envelope_correlation_volume.py:                         36.39 sec    605.5 MB
    - ../examples/simulation/plot_simulated_raw_data_using_subject_anatomy.py:                          34.82 sec    836.6 MB
    - ../examples/preprocessing/plot_ica_comparison.py:                                                 34.54 sec    519.2 MB
    - ../examples/inverse/plot_morph_volume_stc.py:                                                     33.79 sec    604.0 MB
    - ../tutorials/sample-datasets/plot_sleep.py:                                                       31.99 sec    548.1 MB
    - ../examples/decoding/plot_decoding_csp_timefreq.py:                                               31.44 sec      8.2 MB
    - ../tutorials/source-modeling/plot_visualize_stc.py:                                               30.90 sec    657.1 MB
    - ../tutorials/evoked/plot_whitened.py:                                                             29.18 sec    272.0 MB
    - ../examples/decoding/plot_decoding_spoc_CMC.py:                                                   29.00 sec    962.6 MB
    - ../examples/visualization/plot_xhemi.py:                                                          28.83 sec     88.8 MB
    - ../tutorials/preprocessing/plot_45_ica_from_raw.py:                                               28.58 sec    455.3 MB
    - ../tutorials/machine-learning/plot_sensors_decoding.py:                                           28.10 sec    487.1 MB
    - ../tutorials/sample-datasets/plot_brainstorm_phantom_elekta.py:                                   26.81 sec    160.0 MB
    - ../examples/inverse/plot_lcmv_beamformer_volume.py:                                               26.69 sec    845.0 MB
    - ../tutorials/time-freq/plot_sensors_time_frequency.py:                                            23.86 sec    311.2 MB
    - ../tutorials/source-modeling/plot_dipole_fit.py:                                                  23.61 sec      8.3 MB
    - ../examples/inverse/plot_lcmv_beamformer.py:                                                      23.58 sec    798.9 MB
    - ../tutorials/source-modeling/plot_compute_covariance.py:                                          22.60 sec      8.2 MB
    - ../examples/inverse/plot_tf_dics.py:                                                              21.83 sec    486.6 MB
    - ../tutorials/evoked/plot_visualize_evoked.py:                                                     21.69 sec     31.8 MB
    - ../examples/inverse/plot_tf_lcmv.py:                                                              21.33 sec    473.8 MB
    - ../examples/visualization/plot_eeg_on_scalp.py:                                                   20.98 sec     51.6 MB
    - ../examples/inverse/plot_gamma_map_inverse.py:                                                    20.72 sec     69.8 MB
    - ../examples/datasets/plot_opm_data.py:                                                            20.67 sec    944.9 MB
    - ../examples/time_frequency/plot_compute_csd.py:                                                   20.39 sec    230.2 MB
    - ../tutorials/discussions/plot_background_statistics.py:                                           20.36 sec      8.8 MB
    - ../examples/inverse/plot_morph_surface_stc.py:                                                    19.77 sec      8.6 MB
    - ../examples/visualization/plot_evoked_arrowmap.py:                                                19.44 sec     15.0 MB
    - ../tutorials/sample-datasets/plot_brainstorm_phantom_ctf.py:                                      18.53 sec    391.5 MB
    - ../examples/inverse/plot_time_frequency_mixed_norm_inverse.py:                                    18.10 sec      8.5 MB
    - ../tutorials/discussions/plot_background_filtering.py:                                            18.10 sec      8.5 MB
    - ../examples/decoding/plot_decoding_spatio_temporal_source.py:                                     17.51 sec     91.1 MB
    - ../tutorials/source-modeling/plot_source_alignment.py:                                            17.31 sec      9.2 MB
    - ../tutorials/epochs/plot_epoching_and_averaging.py:                                               17.26 sec    100.9 MB
    - ../examples/connectivity/plot_mne_inverse_psi_visual.py:                                          17.19 sec      8.5 MB
    - ../tutorials/machine-learning/plot_receptive_field.py:                                            17.02 sec      8.4 MB
    - ../examples/connectivity/plot_mne_inverse_coherence_epochs.py:                                    16.94 sec      8.6 MB
    - ../tutorials/stats-sensor-space/plot_stats_spatio_temporal_cluster_sensors.py:                    16.92 sec      8.6 MB
    - ../examples/preprocessing/plot_otp.py:                                                            16.44 sec     44.8 MB
    - ../tutorials/stats-source-space/plot_stats_cluster_spatio_temporal.py:                            16.31 sec      8.3 MB
    - ../tutorials/epochs/plot_visualize_epochs.py:                                                     15.98 sec    219.4 MB
    - ../tutorials/evoked/plot_eeg_erp.py:                                                              15.46 sec    127.7 MB
    - ../tutorials/source-modeling/plot_object_source_estimate.py:                                      15.12 sec      8.6 MB
    - ../tutorials/raw/plot_40_visualize_raw.py:                                                        14.71 sec   1868.5 MB
    - ../tutorials/preprocessing/plot_15_handling_bad_channels.py:                                      14.32 sec     15.4 MB
    - ../tutorials/stats-sensor-space/plot_stats_cluster_erp.py:                                        14.19 sec      8.5 MB
    - ../examples/datasets/plot_brainstorm_data.py:                                                     13.84 sec   1450.3 MB
    - ../examples/time_frequency/plot_source_label_time_frequency.py:                                   13.65 sec    171.8 MB
    - ../examples/visualization/plot_topo_customized.py:                                                13.40 sec    216.9 MB
    - ../tutorials/raw/plot_10_raw_overview.py:                                                         13.40 sec    214.9 MB
    - ../tutorials/preprocessing/plot_10_preprocessing_overview.py:                                     12.76 sec    318.7 MB
    - ../examples/inverse/plot_mixed_norm_inverse.py:                                                   12.72 sec     25.3 MB
    - ../tutorials/epochs/plot_object_epochs.py:                                                        12.66 sec    829.3 MB
    - ../examples/preprocessing/plot_interpolate_bad_channels.py:                                       12.63 sec      8.1 MB
    - ../examples/decoding/plot_receptive_field_mtrf.py:                                                12.41 sec      8.5 MB
    - ../examples/io/plot_elekta_epochs.py:                                                             11.84 sec     97.5 MB
    - ../tutorials/misc/plot_ecog.py:                                                                   11.59 sec      9.0 MB
    - ../examples/forward/plot_left_cerebellum_volume_source.py:                                        11.43 sec     47.4 MB
    - ../tutorials/stats-source-space/plot_stats_cluster_time_frequency_repeated_measures_anova.py:     11.24 sec    160.7 MB
    - ../tutorials/preprocessing/plot_50_artifact_correction_ssp.py:                                    11.14 sec    247.4 MB
    - ../examples/datasets/plot_limo_data.py:                                                           10.41 sec    577.9 MB
    - ../tutorials/intro/plot_40_projectors_background.py:                                               9.65 sec    211.7 MB
    - ../examples/time_frequency/plot_time_frequency_erds.py:                                            9.56 sec      8.3 MB
    - ../examples/preprocessing/plot_resample.py:                                                        9.51 sec    588.7 MB
    - ../tutorials/sample-datasets/plot_phantom_4DBTi.py:                                                9.48 sec      8.3 MB
    - ../examples/inverse/plot_mne_crosstalk_function.py:                                                9.48 sec      9.3 MB
    - ../examples/inverse/plot_mne_point_spread_function.py:                                             9.41 sec      8.6 MB
    - ../examples/preprocessing/plot_metadata_query.py:                                                  9.38 sec    581.1 MB
    - ../examples/forward/plot_forward_sensitivity_maps.py:                                              9.35 sec      8.3 MB
    - ../examples/preprocessing/plot_virtual_evoked.py:                                                  9.26 sec      8.2 MB
    - ../examples/time_frequency/plot_time_frequency_simulated.py:                                       9.13 sec     11.0 MB
    - ../tutorials/preprocessing/plot_20_rejecting_bad_data.py:                                          8.72 sec    176.4 MB
    - ../tutorials/epochs/plot_metadata_epochs.py:                                                       8.59 sec      8.3 MB
    - ../tutorials/raw/plot_30_annotate_raw.py:                                                          8.46 sec    216.7 MB
    - ../examples/visualization/plot_evoked_whitening.py:                                                8.40 sec    127.9 MB
    - ../examples/inverse/plot_label_from_stc.py:                                                        8.40 sec      8.8 MB
    - ../examples/visualization/plot_parcellation.py:                                                    8.21 sec      8.8 MB
    - ../tutorials/misc/plot_sensor_locations.py:                                                        7.49 sec    486.9 MB
    - ../tutorials/intro/plot_50_configure_mne.py:                                                       7.47 sec      8.1 MB
    - ../examples/simulation/plot_simulate_raw_data.py:                                                  7.43 sec    275.0 MB
    - ../examples/connectivity/plot_mne_inverse_label_connectivity.py:                                   7.27 sec      9.4 MB
    - ../tutorials/preprocessing/plot_60_maxwell_filtering_sss.py:                                       7.24 sec    486.8 MB
    - ../examples/inverse/plot_vector_mne_solution.py:                                                   7.04 sec     12.4 MB
    - ../examples/inverse/plot_rap_music.py:                                                             6.88 sec      8.3 MB
    - ../tutorials/raw/plot_20_event_arrays.py:                                                          6.81 sec    111.5 MB
    - ../examples/time_frequency/plot_compute_source_psd_epochs.py:                                      6.81 sec     86.0 MB
    - ../tutorials/intro/plot_20_events_from_raw.py:                                                     6.64 sec    214.9 MB
    - ../examples/visualization/plot_3d_to_2d.py:                                                        6.57 sec      8.4 MB
    - ../examples/time_frequency/plot_source_space_time_frequency.py:                                    6.52 sec    586.1 MB
    - ../tutorials/evoked/plot_object_evoked.py:                                                         6.19 sec      8.2 MB
    - ../tutorials/intro/plot_30_info.py:                                                                6.16 sec      8.1 MB
    - ../examples/simulation/plot_simulate_evoked_data.py:                                               5.93 sec    383.0 MB
    - ../examples/decoding/plot_linear_model_patterns.py:                                                5.81 sec   1033.0 MB
    - ../examples/visualization/plot_ssp_projs_sensitivity_map.py:                                       5.76 sec    148.1 MB
    - ../examples/inverse/plot_compute_mne_inverse_volume.py:                                            5.75 sec    581.1 MB
    - ../tutorials/misc/plot_modifying_data_inplace.py:                                                  5.69 sec    464.8 MB
    - ../examples/decoding/plot_decoding_unsupervised_spatial_filter.py:                                 5.62 sec      8.4 MB
    - ../examples/decoding/plot_decoding_time_generalization_conditions.py:                              5.60 sec      8.5 MB
    - ../examples/connectivity/plot_sensor_connectivity.py:                                              5.59 sec      9.8 MB
    - ../examples/preprocessing/plot_xdawn_denoising.py:                                                 5.56 sec    127.9 MB
    - ../tutorials/simulation/plot_creating_data_structures.py:                                          5.50 sec      8.1 MB
    - ../examples/preprocessing/plot_movement_compensation.py:                                           5.47 sec     15.4 MB
    - ../examples/time_frequency/plot_source_power_spectrum.py:                                          5.35 sec    108.0 MB
    - ../examples/connectivity/plot_cwt_sensor_connectivity.py:                                          5.04 sec      8.1 MB
    - ../examples/visualization/plot_meg_sensors.py:                                                     5.02 sec      9.3 MB
    - ../examples/decoding/plot_decoding_xdawn_eeg.py:                                                   4.71 sec      8.2 MB
    - ../examples/time_frequency/plot_compute_raw_data_spectrum.py:                                      4.59 sec    318.3 MB
    - ../examples/visualization/plot_evoked_topomap.py:                                                  4.56 sec      8.3 MB
    - ../tutorials/preprocessing/plot_30_filtering_resampling.py:                                        4.29 sec      8.1 MB
    - ../examples/inverse/plot_custom_inverse_solver.py:                                                 4.25 sec      8.4 MB
    - ../examples/simulation/plot_source_simulator.py:                                                   4.19 sec    113.8 MB
    - ../examples/visualization/plot_roi_erpimage_by_rt.py:                                              4.19 sec      8.1 MB
    - ../examples/inverse/plot_read_inverse.py:                                                          4.13 sec      8.4 MB
    - ../examples/stats/plot_linear_regression_raw.py:                                                   4.08 sec      9.3 MB
    - ../examples/decoding/plot_decoding_csp_eeg.py:                                                     3.86 sec      8.5 MB
    - ../tutorials/epochs/plot_epochs_to_data_frame.py:                                                  3.79 sec      9.3 MB
    - ../examples/inverse/plot_read_source_space.py:                                                     3.74 sec      8.3 MB
    - ../examples/stats/plot_sensor_permutation_test.py:                                                 3.65 sec    251.5 MB
    - ../examples/decoding/plot_ems_filtering.py:                                                        3.63 sec      8.1 MB
    - ../examples/io/plot_read_proj.py:                                                                  3.56 sec     14.0 MB
    - ../examples/io/plot_objects_from_arrays.py:                                                        3.53 sec     75.6 MB
    - ../tutorials/stats-sensor-space/plot_stats_cluster_time_frequency.py:                              3.43 sec      8.1 MB
    - ../examples/stats/plot_sensor_regression.py:                                                       3.41 sec     11.0 MB
    - ../examples/visualization/plot_topo_compare_conditions.py:                                         3.29 sec      8.2 MB
    - ../examples/stats/plot_fdr_stats_evoked.py:                                                        3.26 sec      8.6 MB
    - ../examples/inverse/plot_compute_mne_inverse_epochs_in_label.py:                                   3.25 sec      8.2 MB
    - ../examples/connectivity/plot_mne_inverse_connectivity_spectrum.py:                                3.21 sec      8.7 MB
    - ../examples/stats/plot_cluster_stats_evoked.py:                                                    3.15 sec      8.7 MB
    - ../tutorials/stats-sensor-space/plot_stats_cluster_1samp_test_time_frequency.py:                   3.11 sec      8.5 MB
    - ../examples/datasets/plot_hf_sef_data.py:                                                          2.86 sec      8.2 MB
    - ../examples/preprocessing/plot_find_ecg_artifacts.py:                                              2.83 sec      8.1 MB
    - ../examples/preprocessing/plot_rereference_eeg.py:                                                 2.28 sec    127.8 MB
    - ../examples/preprocessing/plot_define_target_events.py:                                            2.19 sec      8.1 MB
    - ../examples/io/plot_read_and_write_raw_data.py:                                                    2.18 sec     32.4 MB
    - ../examples/io/plot_read_evoked.py:                                                                2.06 sec      8.4 MB
    - ../examples/time_frequency/plot_temporal_whitening.py:                                             2.06 sec      8.2 MB
    - ../examples/inverse/plot_compute_mne_inverse_raw_in_label.py:                                      1.91 sec      8.2 MB
    - ../examples/visualization/plot_channel_epochs_image.py:                                            1.84 sec     11.6 MB
    - ../examples/inverse/plot_snr_estimate.py:                                                          1.80 sec      8.6 MB
    - ../examples/visualization/plot_sensor_noise_level.py:                                              1.72 sec    166.9 MB
    - ../examples/preprocessing/plot_head_positions.py:                                                  1.71 sec      8.1 MB
    - ../examples/preprocessing/plot_eog_artifact_histogram.py:                                          1.67 sec    127.8 MB
    - ../examples/inverse/plot_label_source_activations.py:                                              1.62 sec      8.2 MB
    - ../examples/io/plot_read_epochs.py:                                                                1.53 sec     22.2 MB
    - ../examples/preprocessing/plot_find_eog_artifacts.py:                                              1.31 sec      8.1 MB
    - ../examples/preprocessing/plot_shift_evoked.py:                                                    1.26 sec      8.2 MB
    - ../examples/inverse/plot_read_stc.py:                                                              1.23 sec      8.1 MB
    - ../examples/io/plot_read_events.py:                                                                1.19 sec      8.1 MB
    - ../examples/inverse/plot_label_activation_from_stc.py:                                             1.13 sec      8.1 MB
    - ../examples/io/plot_read_noise_covariance_matrix.py:                                               1.09 sec      8.2 MB
```
</details>

**Comment by banesullivan** [comment]
@choldgraf - I haven't given it a try yet, apologies! I'll try experimenting with it today!

**Comment by choldgraf** [comment]
@banesullivan sounds good - once I get a 👍 from you then I think we should merge, please feel free to give a code review as well!

**Comment by larsoner** [comment]
... and for `matplotlib`:

```
computation time summary:
    - ../examples/animation/animation_demo.py:                                     8.51 sec   0.0 MB
    - ../tutorials/intermediate/constrainedlayout_guide.py:                        5.82 sec   0.0 MB
    - ../examples/style_sheets/style_sheets_reference.py:                          5.44 sec   0.0 MB
    - ../tutorials/colors/colormaps.py:                                            3.92 sec   0.0 MB
    - ../tutorials/intermediate/gridspec.py:                                       3.74 sec   0.0 MB
    - ../examples/lines_bars_and_markers/markevery_demo.py:                        3.71 sec   0.0 MB
    - ../examples/showcase/mandelbrot.py:                                          3.01 sec   0.0 MB
    - ../examples/userdemo/demo_gridspec06.py:                                     1.41 sec   0.0 MB
    - ../tutorials/intermediate/tight_layout_guide.py:                             1.40 sec   0.0 MB
    - ../examples/subplots_axes_and_figures/secondary_axis.py:                     1.39 sec   0.0 MB
    - ../examples/text_labels_and_annotations/demo_text_rotation_mode.py:          1.09 sec   0.0 MB
    - ../examples/subplots_axes_and_figures/demo_tight_layout.py:                  1.08 sec   0.0 MB
    - ../examples/images_contours_and_fields/plot_streamplot.py:                   1.04 sec   0.0 MB
    - ../examples/subplots_axes_and_figures/subplots_demo.py:                      1.03 sec   0.0 MB

```

Given it works on each of these repos I'll go ahead and merge @banesullivan. We can always iterate in subsequent PRs if we want to tweak things!

**Comment by banesullivan** [comment]
Thanks, @larsoner and apologies for not getting around to this! I'll iterate back when I have free time

**Pull request merged**
