### PR TITLE
MNT: Turn the block tuple into a namedtuple

### PR DESCRIPTION
**Pull request by timhoffm**
It's better to give the "Block" concept its own entity and thus be able to access it's attributes by name.

I anticipate that I will need to expand the Block data to support per-block options for #1283, and that expansion will be simpler when blocks are no longer pure tuples. I've decided to split this out for simpler review and advertise this PR as code cleanup.

### CODE REVIEW

**Comment by timhoffm** [comment]
Not quite sure what the failing test for 3.11 / pip mean. Could anybody hint at whether they are related to this PR or whether that pipeline is broken for other reasons? Thanks.

**Comment by lucyleeow** [comment]
I couldn't replicate locally, the rerun test has always been a bit brittle but no idea why `plot_scraper_broken` did not seem to execute in `test_error_messages`. I've rerun the test :shrug: 

I think `save_figures` and docstring of `matplotlib_scraper` needs to be updated (even though `block` is never actually used). The scraper docs should be updated too: https://sphinx-gallery.github.io/dev/advanced.html#write-a-custom-image-scraper

**Comment by lucyleeow** [comment]
Seems spurious, passing now

**Review by larsoner — APPROVED** [review]
Merged `main` in just to make sure everything is still green, good to go from your end @timhoffm ?

**Comment by lucyleeow** [comment]
I think we have to update `scraper.py` and scraper docs, but otherwise LGTM!

**Comment by timhoffm** [comment]
Code-wise this is good to go. It's only documentation that could/should be improved. There are a number of places still describing `block` as tuple. Technically, that is still correct, because a named tuple is still a tuple. But describing it as namedtuple would be more helpful.

I'm a bit tight with time now, so it would take a bit until I get around updating the docs as well. If you want to take this as is or update the docs yourself, that would also be very welcome.

**Comment by lucyleeow** [comment]
Done, @larsoner feel free to merge.

**Comment by larsoner** [comment]
Thanks @timhoffm @lucyleeow !

**Pull request merged**
