### PR TITLE
MRG, ENH: Add private API for external scrapers

### LINKED ISSUE #441: Support for Plotly
Nothing is much clear about the support of sphinx gallery for plotly. It is clear that it just supports matplotlib, seaborn and mayavi. Perhaps more clearity on is it possible to use sphinx gallery for showing plots on plotly?

### PR DESCRIPTION
**Pull request by larsoner**
Closes #441.
Closes #493.

### CODE REVIEW

**Comment by larsoner** [comment]
@emmanuelle @banesullivan let me know if these docs look good to you:

https://880-25860190-gh.circle-artifacts.com/0/rtd_html/configuration.html#image-scrapers
https://880-25860190-gh.circle-artifacts.com/0/rtd_html/advanced.html#integrate-custom-scrapers-with-sphinx-gallery

Once you've implemented the private interface in the modules in the external list, it would be nice to say they can be used by just doing `'image_scrapers': ['pyvista']` or `['plotly']`. So please feel free to make a PR to SG to add a note about this once it's implemented.

**Comment by banesullivan** [comment]
Looks good to me! I just added `_get_sg_image_scraper` to the master branch of PyVista so this will be live on our next release!

**Comment by larsoner** [comment]
Cool. @choldgraf you okay with the updated docs and functionality? Here is what `pyvista` did to make it work (assuming @banesullivan tested it locally and it did indeed work):

https://github.com/pyvista/pyvista/blob/master/pyvista/__init__.py#L34
https://github.com/pyvista/pyvista/blob/master/pyvista/sphinx_gallery.py#L10-L18

**Comment by banesullivan** [comment]
> (assuming @banesullivan tested it locally and it did indeed work)

Tested in d474c94

**Comment by larsoner** [comment]
I meant with the nicer syntax `'image_scrapers': ['pyvista']` (while on this branch)

**Comment by emmanuelle** [comment]
Thanks @larsoner ! Looks good to me.

**Comment by banesullivan** [comment]
> I meant with the nicer syntax 'image_scrapers': ['pyvista'] (while on this branch)

Tested and working on a separate branch shown in my last linked commit ^^^ https://travis-ci.org/pyvista/pyvista/builds/534954544

**Comment by larsoner** [comment]
Okay it's in, @banesullivan after you integrate and release, feel free to open a PR here to update the instructions to say `'pyvista'` works

**Comment by banesullivan** [comment]
> Okay it's in, @banesullivan after you integrate and release, feel free to open a PR here to update the instructions to say 'pyvista' works

@larsoner: PyVista 0.20.3 is out with the `_get_sg_image_scraper` method imlemented. I'm a bit confused on what I need to do here on the SG side... tips?

**Comment by larsoner** [comment]
First make sure the string actually works in your builds. Then update the docs to say something like:

> From PyVista 0.20.3 on, you can simply use `'image_scrapers': ('pyvista',)` to scrape PyVista images

**Comment by larsoner** [comment]
(update the SG gallery docs in the image scrapers section I mean)

Also maybe we should now break up the section a bit. Let me try

**Pull request merged**
