### PR TITLE
ENH: Allow README.rst ext

### LINKED ISSUE #223: Replace examples/README.txt by examples/README.$conf.source_suffix
sphinx's conf.py has a source_suffix field, which can be set (e.g.) to .txt or .rst.  If it is set to .rst (i.e., doc sources have that extension), it would make sense to also look for examples/README.rst instead of examples/README.txt -- this would keep the extension consistent with the rest of the docs.

source_suffix can also be set to a list of extensions, in which case you may just use the first one, or if you really want to do it perfectly, try them one at a time until one matches or raise an error if there are multiple matches -- but that's really not as important, I'd guess.

### LINKED ISSUE #508: Allow .rst extension for README files
https://github.com/sphinx-gallery/sphinx-gallery/blob/cd6eaed237b00ed505b3faa095694c2d66afe49d/sphinx_gallery/gen_gallery.py#L272

Currently, SG forces the required README files to have the `.txt` extension. I imagine almost every project using SG is formatting these README files in RST so allowing an `.rst` extension makes sense.

Why does this matter? It makes viewing the example directory on GitHub a bit more user-friendly as GitHub will render RST properly when the file has an `.rst` extension. See this page for example: https://github.com/pyvista/pyvista/tree/master/examples

A newcomer to the project might explore the example directory in the repo before heading to the gallery on the docs and I'd much rather have a rendered page there than unwelcoming, raw RST

### PR DESCRIPTION
**Pull request by larsoner**
Closes #508.
Closes #223.

@banesullivan @anntzer feel free to give it a shot.

### CODE REVIEW

**Comment by larsoner** [comment]
(@banesullivan I hope you were not really keen to work on this, I looked at the code briefly and realized it was more than a ~5 line change so took the time to refactor a bit...)

**Comment by banesullivan** [comment]
Thanks @larsoner - I was happy to help but hadn't had a chance to look through it so thanks for handling this!

**Comment by larsoner** [comment]
@choldgraf CircleCI indicates that it works, feel free to merge if you're happy.

**Comment by larsoner** [comment]
The only public change is that `.rst` should work in addition to `.txt`. As a side effect it also adds `'app'` to the `gallery_conf` which might be useful to people writing their own scrapers.

**Comment by larsoner** [comment]
(I did not observe any downsides when testing)

**Comment by choldgraf** [comment]
Then let's merge away! This is nice, thanks 😊

**Comment by anntzer** [comment]
Thanks!

**Pull request merged**
